import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Button, Card, Col, Descriptions, Drawer, Form, Input, InputNumber, Modal, Row, Select, Space, Statistic, Switch, Table, Tabs, Tag, Typography, message } from "antd";
import { api } from "@/lib/api";

export const Route = createFileRoute("/_admin/customer-service")({ component: CustomerServicePage });
const { Title, Text, Paragraph } = Typography;
const statusColor:Record<string,string>={active:"green",invisible:"gold",offline:"default",WAITING_FOR_AGENT:"orange",AGENT_ACTIVE:"green",ASSIGNED:"blue",TRANSFER_REQUESTED:"purple",RESOLVED:"cyan",CLOSED:"default"};
const fmt=(v?:string)=>v?new Date(v).toLocaleString():"—";

type SupportConversationRecord = {
 id: number;
 status: string;
 assigned_staff_name?: string | null;
 handoff_reason?: string | null;
};
type SupportMessageRecord = {
 id: number;
 sender_name?: string | null;
 sender_type: string;
 created_at?: string;
 body_text?: string | null;
};
type SupportConversationDetail = {
 conversation: SupportConversationRecord;
 messages: SupportMessageRecord[];
};

function CustomerServicePage(){
 const [loading,setLoading]=useState(false),[overview,setOverview]=useState<any>({staff:{},conversations:{},ai_jobs:{}}),[settings,setSettings]=useState<any>({}),[staff,setStaff]=useState<any[]>([]),[conversations,setConversations]=useState<any[]>([]),[performance,setPerformance]=useState<any[]>([]),[aiJobs,setAiJobs]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[detail,setDetail]=useState<SupportConversationDetail|null>(null),[staffOpen,setStaffOpen]=useState(false);
 const [staffForm]=Form.useForm(),[settingsForm]=Form.useForm();
 const getConversationDetail=async(id:string|number):Promise<SupportConversationDetail>=>{const value=await api.getSupportConversation(id);if(!value?.conversation)throw new Error("Support conversation response is incomplete");return {conversation:value.conversation,messages:Array.isArray(value.messages)?value.messages:[]}};
 const openConversation=async(id:string|number)=>{try{setDetail(await getConversationDetail(id))}catch(e:any){message.error(e.message||"Failed to open support conversation")}};
 const load=async()=>{setLoading(true);try{const [o,s,st,c,p,j,a]=await Promise.all([api.getSupportOverview(),api.getSupportSettings(),api.listSupportStaff(),api.listSupportConversations(),api.getSupportPerformance(),api.listSupportAiJobs(),api.getSupportAudit()]);setOverview(o);setSettings(s);settingsForm.setFieldsValue(s);setStaff(st);setConversations(c);setPerformance(p);setAiJobs(j);setAudit(a)}catch(e:any){message.error(e.message||"Failed to load Customer Service") }finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const activeStaff=useMemo(()=>staff.filter(x=>x.availability_status==="active"),[staff]);
 const createStaff=async()=>{const values=await staffForm.validateFields();await api.createSupportStaff(values);message.success("Customer-service staff account created");setStaffOpen(false);staffForm.resetFields();load()};
 const columns=[{title:"Customer",dataIndex:"customer_display_name",render:(_:any,r:any)=>r.customer_display_name||r.customer_identifier||`Customer ${r.id}`},{title:"Status",dataIndex:"status",render:(v:string)=><Tag color={statusColor[v]}>{v?.replaceAll("_"," ")}</Tag>},{title:"Agent",dataIndex:"assigned_staff_name",render:(v:string)=>v||"Unassigned"},{title:"Handoff",dataIndex:"handoff_reason",render:(v:string)=>v?.replaceAll("_"," ")||"—"},{title:"Last message",dataIndex:"last_message",ellipsis:true},{title:"Updated",dataIndex:"last_message_at",render:fmt},{title:"",render:(_:any,r:any)=><Button size="small" onClick={()=>openConversation(r.id)}>Open</Button>}];
 return <div style={{padding:24}}><Space direction="vertical" size={18} style={{width:"100%"}}><div><Title level={2} style={{marginBottom:4}}>Customer Service</Title><Text type="secondary">Manage live human support, staff accounts, queues, performance, handoff settings, and immutable activity history.</Text></div><Alert showIcon type="info" message="Production boundary" description="AI remains prompt-first. Human Support is an escalation destination, not an AI source. Only one assigned staff member can reply to a conversation."/>
 <Tabs items={[
 {key:"overview",label:"Overview",children:<Space direction="vertical" size={16} style={{width:"100%"}}><Row gutter={[12,12]}>{[["Active staff",overview.staff?.staff_active||0],["Waiting",overview.conversations?.waiting||0],["Agent active",overview.conversations?.active||0],["AI queued",overview.ai_jobs?.queued||0],["AI processing",overview.ai_jobs?.processing||0],["AI retrying",overview.ai_jobs?.retrying||0],["AI completed 24h",overview.ai_jobs?.completed_24h||0],["AI failed 24h",overview.ai_jobs?.failed_24h||0]].map(([label,value])=><Col xs={12} md={8} xl={4} key={String(label)}><Card><Statistic title={label} value={value}/></Card></Col>)}</Row><Card title="Live queue" extra={<Button onClick={load} loading={loading}>Refresh</Button>}><Table rowKey="id" size="small" dataSource={conversations.slice(0,20)} columns={columns as any} pagination={false}/></Card></Space>},
 {key:"live",label:"Live Conversations",children:<Card extra={<Button onClick={load}>Refresh</Button>}><Table rowKey="id" dataSource={conversations} columns={columns as any}/></Card>},
 {key:"staff",label:"Staff Accounts",children:<Card extra={<Button type="primary" onClick={()=>setStaffOpen(true)}>Create staff account</Button>}><Table rowKey="id" dataSource={staff} columns={[{title:"Staff",dataIndex:"display_name"},{title:"Email",dataIndex:"email"},{title:"Presence",dataIndex:"availability_status",render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>},{title:"Account",dataIndex:"account_status"},{title:"Timezone",render:(_:any,r:any)=>r.use_platform_timezone?"Platform default":r.timezone||"UTC"},{title:"Capacity",dataIndex:"max_active_conversations"},{title:"Actions",render:(_:any,r:any)=><Space><Button size="small" onClick={async()=>{await api.updateSupportStaff(r.id,{account_status:r.account_status==='active'?'inactive':'active'});message.success(r.account_status==='active'?'Staff account deactivated':'Staff account activated');load()}}>{r.account_status==='active'?'Deactivate':'Activate'}</Button><Button size="small" danger onClick={()=>Modal.confirm({title:`Force logout ${r.display_name}?`,onOk:async()=>{await api.forceLogoutSupportStaff(r.id);message.success("Staff sessions revoked");load()}})}>Force logout</Button><Button size="small" onClick={()=>{let temp="";Modal.confirm({title:"Set temporary password",content:<Input.Password minLength={12} placeholder="At least 12 characters" onChange={e=>temp=e.target.value}/>,onOk:async()=>{if(temp.length<12)throw new Error("Password must be at least 12 characters");await api.resetSupportStaffPassword(r.id,temp);message.success("Temporary password set")}})}}>Reset password</Button></Space>}]} /></Card>},
 {key:"performance",label:"Performance",children:<Card><Table rowKey="id" dataSource={performance} columns={[{title:"Staff",dataIndex:"display_name"},{title:"Conversations",dataIndex:"conversations_served"},{title:"Resolved",dataIndex:"resolved_conversations"},{title:"Replies",dataIndex:"replies_sent"},{title:"Sentences",dataIndex:"sentences_sent"},{title:"Avg first response",dataIndex:"avg_first_response_seconds",render:(v:number)=>`${v||0}s`},{title:"Avg duration",dataIndex:"avg_conversation_seconds",render:(v:number)=>`${Math.round((v||0)/60)}m`}]} /></Card>},
 {key:"settings",label:"Handoff Settings",children:<Card><Form form={settingsForm} layout="vertical" onFinish={async values=>{await api.updateSupportSettings(values);message.success("Human handoff settings saved");load()}}><Row gutter={16}><Col span={24}><Form.Item name="human_support_enabled" label="Enable Human Customer Service Handoff" valuePropName="checked"><Switch/></Form.Item></Col><Col md={12} xs={24}><Form.Item name="handoff_button_text" label="Handoff button text"><Input/></Form.Item></Col><Col md={12} xs={24}><Form.Item name="maximum_clarification_attempts" label="Maximum clarification attempts"><InputNumber min={0} max={10} style={{width:"100%"}}/></Form.Item></Col><Col span={24}><Form.Item name="ai_suggestion_message" label="AI suggestion message"><Input.TextArea rows={2}/></Form.Item></Col><Col span={24}><Form.Item name="waiting_message" label="Waiting message"><Input.TextArea rows={2}/></Form.Item></Col><Col span={24}><Form.Item name="no_staff_online_message" label="No staff online message"><Input.TextArea rows={2}/></Form.Item></Col>
<Col span={24}><Title level={4}>AI Processing Experience</Title><Paragraph type="secondary">These temporary messages are ephemeral interface indicators. They are never stored as chat messages and disappear when the final AI reply arrives.</Paragraph></Col>
<Col md={8} xs={24}><Form.Item name="processing_message_enabled" label="Enable processing message" valuePropName="checked"><Switch/></Form.Item></Col>
<Col md={8} xs={24}><Form.Item name="allow_messages_while_ai_processing" label="Allow queued customer messages" valuePropName="checked"><Switch/></Form.Item></Col>
<Col md={8} xs={24}><Form.Item name="return_to_ai_on_resolve" label="Return customer to AI after resolve" valuePropName="checked"><Switch/></Form.Item></Col>
<Col span={24}><Form.Item name="processing_message_text" label="Primary processing message"><Input.TextArea rows={2} placeholder="Jerry is preparing your answer…"/></Form.Item></Col>
<Col span={24}><Form.Item name="processing_message_secondary_text" label="Secondary waiting message"><Input.TextArea rows={2} placeholder="Jerry is still working on your answer…"/></Form.Item></Col>
<Col md={8} xs={24}><Form.Item name="processing_message_delay_ms" label="Show after (ms)"><InputNumber min={0} max={10000} step={100} style={{width:"100%"}}/></Form.Item></Col>
<Col md={8} xs={24}><Form.Item name="processing_message_secondary_delay_ms" label="Secondary after (ms)"><InputNumber min={1000} max={120000} step={1000} style={{width:"100%"}}/></Form.Item></Col>
<Col md={8} xs={24}><Form.Item name="processing_message_max_visible_ms" label="Maximum visible (ms)"><InputNumber min={5000} max={300000} step={1000} style={{width:"100%"}}/></Form.Item></Col>
<Col span={24}><Form.Item name="provider_failure_message" label="Safe message after all AI retries fail"><Input.TextArea rows={2}/></Form.Item></Col>
<Col span={24}><Title level={4}>Human Handoff</Title></Col>
<Col md={12} xs={24}><Form.Item name="platform_timezone" label="Platform timezone"><Input placeholder="Asia/Phnom_Penh"/></Form.Item></Col><Col md={12} xs={24}><Form.Item name="allow_staff_timezone_override" label="Allow personal timezone" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_customer_request" label="Customer requests human" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_not_understood" label="Request not understood" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_provider_error" label="AI provider failure" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_outside_scope" label="Outside assistant scope" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_account_investigation" label="Account investigation" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_manual_action" label="Manual action required" valuePropName="checked"><Switch/></Form.Item></Col><Col md={8} xs={24}><Form.Item name="trigger_clarification_limit" label="Clarification limit" valuePropName="checked"><Switch/></Form.Item></Col><Col span={24}><Form.Item name="escalation_keywords" label="Admin escalation keywords"><Input.TextArea rows={2}/></Form.Item></Col></Row><Button type="primary" htmlType="submit">Save settings</Button></Form></Card>},
 {key:"ai-delivery",label:"AI Delivery",children:<Space direction="vertical" size={12} style={{width:"100%"}}><Alert type="info" showIcon message="Persistent plain-text AI worker" description="Customer messages are stored immediately. AI jobs retry in the background, and the final answer is delivered by WebSocket. Temporary processing text is not stored in the conversation."/><Card extra={<Button onClick={load} loading={loading}>Refresh</Button>}><Table rowKey="id" dataSource={aiJobs} scroll={{x:1000}} columns={[{title:"Job",dataIndex:"public_id",ellipsis:true},{title:"Status",dataIndex:"status",render:(v:string)=><Tag color={v==="COMPLETED"?"green":v==="FAILED"?"red":v==="RETRYING"?"orange":v==="PROCESSING"?"blue":"default"}>{v}</Tag>},{title:"Customer",render:(_:any,r:any)=>r.customer_display_name||r.customer_identifier||"Customer"},{title:"Customer message",dataIndex:"customer_message",ellipsis:true},{title:"Attempts",render:(_:any,r:any)=>`${r.attempt_count||0}/${r.max_attempts||3}`},{title:"Provider",dataIndex:"provider_status",render:(v:string)=>v||"—"},{title:"Error",render:(_:any,r:any)=>r.last_error_code?`${r.last_error_code}: ${r.last_error_detail||""}`:"—",ellipsis:true},{title:"Created",dataIndex:"created_at",render:fmt},{title:"Completed",dataIndex:"completed_at",render:fmt}]} /></Card></Space>},
 {key:"audit",label:"Audit Log",children:<Card><Table rowKey="id" dataSource={audit} columns={[{title:"Time",dataIndex:"created_at",render:fmt},{title:"Actor",render:(_:any,r:any)=>`${r.actor_type}: ${r.actor_identifier}`},{title:"Action",dataIndex:"action_key"},{title:"Entity",render:(_:any,r:any)=>`${r.entity_type} #${r.entity_id||""}`},{title:"Detail",dataIndex:"detail",ellipsis:true}]}/></Card>}
 ]}/></Space>
 <Modal title="Create customer-service staff" open={staffOpen} onCancel={()=>setStaffOpen(false)} onOk={createStaff} okText="Create account"><Form form={staffForm} layout="vertical" initialValues={{max_active_conversations:5,use_platform_timezone:true,permissions:["support.conversations.view_own","support.conversations.view_team","support.conversations.accept","support.conversations.reply","support.conversations.transfer","support.conversations.resolve","support.notes.create","support.reports.view_own"]}}><Form.Item name="display_name" label="Display name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="email" label="Login email" rules={[{required:true,type:"email"}]}><Input/></Form.Item><Form.Item name="temporary_password" label="Temporary password" rules={[{required:true,min:12}]}><Input.Password/></Form.Item><Form.Item name="max_active_conversations" label="Maximum active conversations"><InputNumber min={1} max={50}/></Form.Item><Form.Item name="personal_timezone_allowed" label="Allow personal timezone" valuePropName="checked"><Switch/></Form.Item><Paragraph type="secondary">The staff member must change the temporary password after login. Staff cannot access Admin.</Paragraph></Form></Modal>
 <Drawer width={620} title="Support conversation" open={!!detail} onClose={()=>setDetail(null)}>{detail ? <><Descriptions column={1} size="small" bordered items={[{key:"status",label:"Status",children:detail.conversation.status},{key:"agent",label:"Assigned staff",children:detail.conversation.assigned_staff_name||"Unassigned"},{key:"reason",label:"Handoff reason",children:detail.conversation.handoff_reason||"—"}]}/><Space style={{marginTop:14}}><Select style={{width:240}} placeholder="Assign active staff" options={activeStaff.map(x=>({value:x.id,label:x.display_name}))} onChange={async staffId=>{await api.assignSupportConversation(detail.conversation.id,staffId);message.success("Conversation assigned");setDetail(await getConversationDetail(detail.conversation.id));load()}}/><Button onClick={async()=>{const action=detail.conversation.status==='RESOLVED'?'reopen':'resolve';await api.resolveSupportConversation(detail.conversation.id,action);message.success(`Conversation ${action}d`);setDetail(await getConversationDetail(detail.conversation.id));load()}}>{detail.conversation.status==='RESOLVED'?'Reopen':'Resolve'}</Button></Space><Title level={4} style={{marginTop:20}}>Unified AI and human timeline</Title><Space direction="vertical" style={{width:"100%"}}>{detail.messages.map((m)=><Card size="small" key={m.id} title={`${m.sender_name||m.sender_type} · ${fmt(m.created_at)}`}><Paragraph style={{whiteSpace:"pre-wrap",marginBottom:0}}>{m.body_text}</Paragraph></Card>)}</Space></> : null}</Drawer></div>
}
