import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Alert, Button, Drawer, Form, Image, Input, InputNumber, Popconfirm, Select, Space, Table, Tag, Upload, message } from "antd";
import { DeleteOutlined, EditOutlined, LinkOutlined, PlusOutlined, ReloadOutlined, UploadOutlined } from "@ant-design/icons";
import { api } from "@/lib/api";
export const Route = createFileRoute("/_admin/action-buttons")({ component: GlobalButtonsPage });
function GlobalButtonsPage(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[editing,setEditing]=useState<any|null>(null),[platformName,setPlatformName]=useState(""); const [form]=Form.useForm();
 const load=async()=>{setLoading(true);try{const [buttons,context]=await Promise.all([api.list("action-buttons"),api.getPlatformContext()]);if(!(context as any)?.platform)throw new Error("Active platform context is unavailable");setRows(buttons as any[]);setPlatformName((context as any).platform.platform_name||"");}catch(e:any){message.error(e?.message||"Failed to load global buttons");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const open=(row?:any)=>{const value=row||{button_key:"",label:"",subtitle:"",action_type:"url",target:"same_window",status:"active",sort_order:100,capability:"general"};setEditing(value);form.setFieldsValue(value);};
 const save=async()=>{const values=await form.validateFields();try{if(editing?.id)await api.update("action-buttons",editing.id,values);else await api.create("action-buttons",values);message.success(editing?.id?"Global button updated":"Global button created");setEditing(null);await load();}catch(e:any){message.error(e?.message||"Save failed");}};
 const remove=async(id:number)=>{try{await api.remove("action-buttons",id);message.success("Global button archived");await load();}catch(e:any){message.error(e?.message||"Delete failed");}};
 const upload=async(file:File)=>{try{const result=await api.upload(file);form.setFieldValue("icon_url",result.url);message.success("Icon uploaded");}catch(e:any){message.error(e?.message||"Upload failed");}return false;};
 return <><div className="bdg-filters" style={{marginBottom:12}}><div style={{flex:1}}><h2 style={{margin:0}}>Global Buttons</h2><div style={{color:"#8ea0bd",fontSize:12}}>One label and action for {platformName||"the active platform"}. The same button is used in every customer language.</div></div><Button icon={<ReloadOutlined/>} onClick={load}>Refresh</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>open()}>New button</Button></div>
 <Alert showIcon type="info" message="Global label contract" description="Localized Hindi and other per-language labels are retired. Configure one clear label for all customers." style={{marginBottom:12}}/>
 <Table rowKey="id" loading={loading} dataSource={rows} pagination={{pageSize:20}} columns={[
 {title:"Button",render:(_:any,row:any)=><Space>{row.icon_url?<Image preview={false} src={row.icon_url} width={32} height={32}/>:<LinkOutlined/>}<div><b>{row.label}</b><div style={{color:"#8ea0bd",fontSize:12}}>{row.subtitle||row.button_key}</div></div></Space>},
 {title:"Action",render:(_:any,row:any)=><><Tag color="blue">{row.action_type}</Tag><div>{row.url}</div></>},
 {title:"Status",dataIndex:"status",render:(v:string)=><Tag color={v==="active"?"green":"default"}>{v}</Tag>},
 {title:"Order",dataIndex:"sort_order",width:80},
 {title:"Actions",width:140,render:(_:any,row:any)=><Space><Button size="small" icon={<EditOutlined/>} onClick={()=>open(row)}>Edit</Button><Popconfirm title="Archive this global button?" onConfirm={()=>remove(row.id)}><Button size="small" danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}
 ]}/>
 <Drawer open={!!editing} onClose={()=>setEditing(null)} width={680} title={editing?.id?"Edit global button":"Create global button"} extra={<Space><Button onClick={()=>setEditing(null)}>Cancel</Button><Button type="primary" onClick={save}>Save</Button></Space>}><Form form={form} layout="vertical"><Form.Item label="Button label" name="label" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="Optional subtitle" name="subtitle"><Input/></Form.Item><Form.Item label="Stable key" name="button_key"><Input/></Form.Item><Space.Compact style={{width:"100%"}}><Form.Item style={{width:"34%"}} label="Action type" name="action_type"><Select options={["url","deep_link","internal","chat_prompt"].map(value=>({value,label:value}))}/></Form.Item><Form.Item style={{width:"66%"}} label="URL or action" name="url" rules={[{required:true}]}><Input/></Form.Item></Space.Compact><Space.Compact style={{width:"100%"}}><Form.Item style={{width:"50%"}} label="Target" name="target"><Select options={[{value:"same_window",label:"Same window"},{value:"new_window",label:"New window"}]}/></Form.Item><Form.Item style={{width:"50%"}} label="Status" name="status"><Select options={[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"}]}/></Form.Item></Space.Compact><Form.Item label="Display order" name="sort_order"><InputNumber min={1}/></Form.Item><Form.Item label="Icon URL" name="icon_url"><Input/></Form.Item><Upload showUploadList={false} beforeUpload={upload}><Button icon={<UploadOutlined/>}>Upload icon</Button></Upload></Form></Drawer></>;
}
