/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminThemeSettingsRouteImport } from './routes/_admin.theme-settings'
import { Route as AdminSupportSettingsRouteImport } from './routes/_admin.support-settings'
import { Route as AdminSiteContentRouteImport } from './routes/_admin.site-content'
import { Route as AdminPromptHistoryRouteImport } from './routes/_admin.prompt-history'
import { Route as AdminHelpCardsRouteImport } from './routes/_admin.help-cards'
import { Route as AdminGuideImagesRouteImport } from './routes/_admin.guide-images'
import { Route as AdminFaqRouteImport } from './routes/_admin.faq'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminChatQuickRepliesRouteImport } from './routes/_admin.chat-quick-replies'
import { Route as AdminChatLogsRouteImport } from './routes/_admin.chat-logs'
import { Route as AdminUnmatchedQuestionsRouteImport } from './routes/_admin.unmatched-questions'
import { Route as AdminCategoriesRouteImport } from './routes/_admin.categories'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin.audit-logs'
import { Route as AdminAiPromptManagerRouteImport } from './routes/_admin.ai-prompt-manager'
import { Route as AdminSmartMatchGuidesRouteImport } from './routes/_admin.smart-match-guides'
import { Route as AdminAiKnowledgeRouteImport } from './routes/_admin.ai-knowledge'
import { Route as AdminAiDiagnosticsRouteImport } from './routes/_admin.ai-diagnostics'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin-users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeSettingsRoute = AdminThemeSettingsRouteImport.update({
  id: '/theme-settings',
  path: '/theme-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportSettingsRoute = AdminSupportSettingsRouteImport.update({
  id: '/support-settings',
  path: '/support-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmartMatchGuidesRoute = AdminSmartMatchGuidesRouteImport.update({
  id: '/smart-match-guides',
  path: '/smart-match-guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptHistoryRoute = AdminPromptHistoryRouteImport.update({
  id: '/prompt-history',
  path: '/prompt-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpCardsRoute = AdminHelpCardsRouteImport.update({
  id: '/help-cards',
  path: '/help-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideImagesRoute = AdminGuideImagesRouteImport.update({
  id: '/guide-images',
  path: '/guide-images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatQuickRepliesRoute = AdminChatQuickRepliesRouteImport.update({
  id: '/chat-quick-replies',
  path: '/chat-quick-replies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatLogsRoute = AdminChatLogsRouteImport.update({
  id: '/chat-logs',
  path: '/chat-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnmatchedQuestionsRoute = AdminUnmatchedQuestionsRouteImport.update({
  id: '/unmatched-questions',
  path: '/unmatched-questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiPromptManagerRoute = AdminAiPromptManagerRouteImport.update({
  id: '/ai-prompt-manager',
  path: '/ai-prompt-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiKnowledgeRoute = AdminAiKnowledgeRouteImport.update({
  id: '/ai-knowledge',
  path: '/ai-knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiDiagnosticsRoute = AdminAiDiagnosticsRouteImport.update({
  id: '/ai-diagnostics',
  path: '/ai-diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/ai-knowledge': typeof AdminAiKnowledgeRoute
  '/ai-prompt-manager': typeof AdminAiPromptManagerRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/categories': typeof AdminCategoriesRoute
  '/chat-logs': typeof AdminChatLogsRoute
  '/unmatched-questions': typeof AdminUnmatchedQuestionsRoute
  '/chat-quick-replies': typeof AdminChatQuickRepliesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/faq': typeof AdminFaqRoute
  '/guide-images': typeof AdminGuideImagesRoute
  '/help-cards': typeof AdminHelpCardsRoute
  '/prompt-history': typeof AdminPromptHistoryRoute
  '/smart-match-guides': typeof AdminSmartMatchGuidesRoute
  '/site-content': typeof AdminSiteContentRoute
  '/support-settings': typeof AdminSupportSettingsRoute
  '/theme-settings': typeof AdminThemeSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/ai-knowledge': typeof AdminAiKnowledgeRoute
  '/ai-prompt-manager': typeof AdminAiPromptManagerRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/categories': typeof AdminCategoriesRoute
  '/chat-logs': typeof AdminChatLogsRoute
  '/unmatched-questions': typeof AdminUnmatchedQuestionsRoute
  '/chat-quick-replies': typeof AdminChatQuickRepliesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/faq': typeof AdminFaqRoute
  '/guide-images': typeof AdminGuideImagesRoute
  '/help-cards': typeof AdminHelpCardsRoute
  '/prompt-history': typeof AdminPromptHistoryRoute
  '/smart-match-guides': typeof AdminSmartMatchGuidesRoute
  '/site-content': typeof AdminSiteContentRoute
  '/support-settings': typeof AdminSupportSettingsRoute
  '/theme-settings': typeof AdminThemeSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin-users': typeof AdminAdminUsersRoute
  '/_admin/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/_admin/ai-knowledge': typeof AdminAiKnowledgeRoute
  '/_admin/ai-prompt-manager': typeof AdminAiPromptManagerRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/chat-logs': typeof AdminChatLogsRoute
  '/_admin/unmatched-questions': typeof AdminUnmatchedQuestionsRoute
  '/_admin/chat-quick-replies': typeof AdminChatQuickRepliesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/faq': typeof AdminFaqRoute
  '/_admin/guide-images': typeof AdminGuideImagesRoute
  '/_admin/help-cards': typeof AdminHelpCardsRoute
  '/_admin/prompt-history': typeof AdminPromptHistoryRoute
  '/_admin/smart-match-guides': typeof AdminSmartMatchGuidesRoute
  '/_admin/site-content': typeof AdminSiteContentRoute
  '/_admin/support-settings': typeof AdminSupportSettingsRoute
  '/_admin/theme-settings': typeof AdminThemeSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-users'
    | '/ai-diagnostics'
    | '/ai-knowledge'
    | '/ai-prompt-manager'
    | '/audit-logs'
    | '/categories'
    | '/chat-logs'
    | '/unmatched-questions'
    | '/chat-quick-replies'
    | '/dashboard'
    | '/faq'
    | '/guide-images'
    | '/help-cards'
    | '/prompt-history'
    | '/smart-match-guides'
    | '/site-content'
    | '/support-settings'
    | '/theme-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-users'
    | '/ai-diagnostics'
    | '/ai-knowledge'
    | '/ai-prompt-manager'
    | '/audit-logs'
    | '/categories'
    | '/chat-logs'
    | '/unmatched-questions'
    | '/chat-quick-replies'
    | '/dashboard'
    | '/faq'
    | '/guide-images'
    | '/help-cards'
    | '/prompt-history'
    | '/smart-match-guides'
    | '/site-content'
    | '/support-settings'
    | '/theme-settings'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/admin-users'
    | '/_admin/ai-diagnostics'
    | '/_admin/ai-knowledge'
    | '/_admin/ai-prompt-manager'
    | '/_admin/audit-logs'
    | '/_admin/categories'
    | '/_admin/chat-logs'
    | '/_admin/unmatched-questions'
    | '/_admin/chat-quick-replies'
    | '/_admin/dashboard'
    | '/_admin/faq'
    | '/_admin/guide-images'
    | '/_admin/help-cards'
    | '/_admin/prompt-history'
    | '/_admin/smart-match-guides'
    | '/_admin/site-content'
    | '/_admin/support-settings'
    | '/_admin/theme-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/theme-settings': {
      id: '/_admin/theme-settings'
      path: '/theme-settings'
      fullPath: '/theme-settings'
      preLoaderRoute: typeof AdminThemeSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support-settings': {
      id: '/_admin/support-settings'
      path: '/support-settings'
      fullPath: '/support-settings'
      preLoaderRoute: typeof AdminSupportSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/site-content': {
      id: '/_admin/site-content'
      path: '/site-content'
      fullPath: '/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/smart-match-guides': {
      id: '/_admin/smart-match-guides'
      path: '/smart-match-guides'
      fullPath: '/smart-match-guides'
      preLoaderRoute: typeof AdminSmartMatchGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/prompt-history': {
      id: '/_admin/prompt-history'
      path: '/prompt-history'
      fullPath: '/prompt-history'
      preLoaderRoute: typeof AdminPromptHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/help-cards': {
      id: '/_admin/help-cards'
      path: '/help-cards'
      fullPath: '/help-cards'
      preLoaderRoute: typeof AdminHelpCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/guide-images': {
      id: '/_admin/guide-images'
      path: '/guide-images'
      fullPath: '/guide-images'
      preLoaderRoute: typeof AdminGuideImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faq': {
      id: '/_admin/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/chat-quick-replies': {
      id: '/_admin/chat-quick-replies'
      path: '/chat-quick-replies'
      fullPath: '/chat-quick-replies'
      preLoaderRoute: typeof AdminChatQuickRepliesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/chat-logs': {
      id: '/_admin/chat-logs'
      path: '/chat-logs'
      fullPath: '/chat-logs'
      preLoaderRoute: typeof AdminChatLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/unmatched-questions': {
      id: '/_admin/unmatched-questions'
      path: '/unmatched-questions'
      fullPath: '/unmatched-questions'
      preLoaderRoute: typeof AdminUnmatchedQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-prompt-manager': {
      id: '/_admin/ai-prompt-manager'
      path: '/ai-prompt-manager'
      fullPath: '/ai-prompt-manager'
      preLoaderRoute: typeof AdminAiPromptManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-knowledge': {
      id: '/_admin/ai-knowledge'
      path: '/ai-knowledge'
      fullPath: '/ai-knowledge'
      preLoaderRoute: typeof AdminAiKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-diagnostics': {
      id: '/_admin/ai-diagnostics'
      path: '/ai-diagnostics'
      fullPath: '/ai-diagnostics'
      preLoaderRoute: typeof AdminAiDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin-users': {
      id: '/_admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAiDiagnosticsRoute: typeof AdminAiDiagnosticsRoute
  AdminAiKnowledgeRoute: typeof AdminAiKnowledgeRoute
  AdminAiPromptManagerRoute: typeof AdminAiPromptManagerRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatLogsRoute: typeof AdminChatLogsRoute
  AdminUnmatchedQuestionsRoute: typeof AdminUnmatchedQuestionsRoute
  AdminChatQuickRepliesRoute: typeof AdminChatQuickRepliesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminGuideImagesRoute: typeof AdminGuideImagesRoute
  AdminHelpCardsRoute: typeof AdminHelpCardsRoute
  AdminPromptHistoryRoute: typeof AdminPromptHistoryRoute
  AdminSmartMatchGuidesRoute: typeof AdminSmartMatchGuidesRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminSupportSettingsRoute: typeof AdminSupportSettingsRoute
  AdminThemeSettingsRoute: typeof AdminThemeSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAiDiagnosticsRoute: AdminAiDiagnosticsRoute,
  AdminAiKnowledgeRoute: AdminAiKnowledgeRoute,
  AdminAiPromptManagerRoute: AdminAiPromptManagerRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatLogsRoute: AdminChatLogsRoute,
  AdminUnmatchedQuestionsRoute: AdminUnmatchedQuestionsRoute,
  AdminChatQuickRepliesRoute: AdminChatQuickRepliesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminGuideImagesRoute: AdminGuideImagesRoute,
  AdminHelpCardsRoute: AdminHelpCardsRoute,
  AdminPromptHistoryRoute: AdminPromptHistoryRoute,
  AdminSmartMatchGuidesRoute: AdminSmartMatchGuidesRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminSupportSettingsRoute: AdminSupportSettingsRoute,
  AdminThemeSettingsRoute: AdminThemeSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
