const API = window.APP_CONFIG.API_BASE;
const $ = (id) => document.getElementById(id);
const state = { token: localStorage.getItem('admin_token') || '', categories: [], guides: [], faqs: [], knowledge: [], logs: [], audit: [], settings: {}, aiPrompts: [], promptVersions: [], aiSettings: {}, sessions: [], siteContent: {} };

async function api(path, options = {}) {
  const headers = { ...(options.headers || {}) };
  if (!(options.body instanceof FormData)) headers['Content-Type'] = 'application/json';
  if (state.token) headers.Authorization = `Bearer ${state.token}`;
  const res = await fetch(`${API}${path}`, { ...options, headers });
  if (!res.ok) throw new Error(await res.text());
  return res.status === 204 ? null : res.json();
}
function toast(msg) { const t = $('toast'); t.textContent = msg; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 2600); }
function esc(text = '') { return String(text).replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch])); }
function lines(text = '') { return String(text || '').split('\n').map(x => x.trim()).filter(Boolean); }
function numberVal(id, fallback = 100) { const n = Number($(id).value); return Number.isFinite(n) ? n : fallback; }
function bool(v) { return v === true || v === 'true'; }
function safe(fn) { return fn().catch(err => { console.error(err); toast('Action failed. Check console.'); }); }

function showApp() { $('loginScreen').classList.add('hidden'); $('appScreen').classList.remove('hidden'); refreshAll(); }
function showLogin() { $('loginScreen').classList.remove('hidden'); $('appScreen').classList.add('hidden'); }
$('loginForm').addEventListener('submit', async (e) => { e.preventDefault(); try { const data = await api('/auth/login', { method:'POST', body: JSON.stringify({ email:$('email').value, password:$('password').value }) }); state.token = data.access_token; localStorage.setItem('admin_token', state.token); toast('Logged in'); showApp(); } catch (err) { console.error(err); toast('Login failed. Check password.'); } });
$('logoutBtn').addEventListener('click', () => { localStorage.removeItem('admin_token'); state.token = ''; showLogin(); });

$('openGuide').href = window.APP_CONFIG.GUIDE_URL || 'http://localhost:5501';
$('openChat').href = window.APP_CONFIG.CHAT_URL || 'http://localhost:5502';
$('refreshBtn').addEventListener('click', refreshAll);
document.querySelectorAll('.nav').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.nav').forEach(x => x.classList.remove('active')); document.querySelectorAll('.view').forEach(x => x.classList.remove('active-view')); btn.classList.add('active'); $(btn.dataset.view).classList.add('active-view'); $('viewTitle').textContent = btn.textContent; }));

async function refreshAll() {
  await loadSettings().catch(console.error);
  await Promise.allSettled([loadSiteContent(), loadCategories(), loadGuides(), loadFaqs(), loadKnowledge(), loadAiMode(), loadLogs(), loadAudit(), loadDiagnostics()]);
  $('statGuides').textContent = state.guides.length;
  $('statFaqs').textContent = state.faqs.length;
  $('statPrompts').textContent = state.aiPrompts.length;
  $('statLogs').textContent = state.logs.length;
  $('statAudit').textContent = state.audit.length;
}
async function loadSettings() { state.settings = await api('/settings'); const s = state.settings; $('siteName').textContent = s.app_name || 'Admin CMS'; $('sideLogo').textContent = s.logo_text || 'BDG'; $('themeAppName').value = s.app_name || ''; $('themeLogoText').value = s.logo_text || ''; $('themeBannerTitle').value = s.banner_title || ''; $('themeBannerSubtitle').value = s.banner_subtitle || ''; $('themeSupportLink').value = s.support_link || ''; $('themePrimaryColor').value = s.primary_color || '#f7c948'; if (s.primary_color) document.documentElement.style.setProperty('--gold', s.primary_color); }
$('themeForm').addEventListener('submit', e => safe(async () => { e.preventDefault(); await api('/admin/settings', { method:'PUT', body: JSON.stringify({ app_name:$('themeAppName').value, logo_text:$('themeLogoText').value, banner_title:$('themeBannerTitle').value, banner_subtitle:$('themeBannerSubtitle').value, support_link:$('themeSupportLink').value, primary_color:$('themePrimaryColor').value }) }); toast('Theme saved'); await loadSettings(); }));

async function loadSiteContent() { state.siteContent = await api('/admin/site-content'); renderContentBlocks(); renderHomeSections(); renderPopular(); renderNavigation(); renderQuick(); }
function renderContentBlocks() { $('contentBlocks').innerHTML = (state.siteContent.blocks || []).map(b => `<label>${esc(b.label)}${b.input_type === 'textarea' ? `<textarea data-block-key="${esc(b.block_key)}" data-label="${esc(b.label)}" data-type="${esc(b.input_type)}" data-sort="${esc(b.sort_order)}" rows="3">${esc(b.value)}</textarea>` : `<input data-block-key="${esc(b.block_key)}" data-label="${esc(b.label)}" data-type="${esc(b.input_type)}" data-sort="${esc(b.sort_order)}" value="${esc(b.value)}"/>`}</label>`).join(''); }
$('saveContentBlocks').addEventListener('click', () => safe(async () => { const blocks = [...document.querySelectorAll('[data-block-key]')].map(el => ({ block_key: el.dataset.blockKey, label: el.dataset.label, input_type: el.dataset.type, sort_order: Number(el.dataset.sort || 100), value: el.value })); await api('/admin/site-content/bulk', { method:'PUT', body: JSON.stringify({ blocks }) }); toast('Guide site text saved'); await loadSiteContent(); }));
function renderHomeSections() { $('homeSections').innerHTML = (state.siteContent.home_sections || []).map(s => `<div class="item slim"><div><h3>${esc(s.title)}</h3><span class="badge">${esc(s.section_key)} · order ${esc(s.sort_order)}</span></div><label class="switch"><input type="checkbox" ${s.enabled?'checked':''} onchange="toggleHomeSection('${esc(s.section_key)}', this.checked)"> enabled</label></div>`).join(''); }
window.toggleHomeSection = (key, checked) => safe(async () => { const s = (state.siteContent.home_sections || []).find(x => x.section_key === key); await api(`/admin/home-sections/${key}`, { method:'PUT', body: JSON.stringify({ title: s?.title || key, enabled: checked, sort_order: s?.sort_order || 100 }) }); toast('Section updated'); await loadSiteContent(); });
function renderPopular() { $('popularList').innerHTML = (state.siteContent.popular_help || []).map(c => `<div class="item slim"><div><h3>${esc(c.icon)} ${esc(c.title)}</h3><p>${esc(c.subtitle)}</p><span class="badge">${esc(c.status)} · ${esc(c.query || '-')}</span></div><div class="mini-actions"><button onclick="editPopular(${c.id})">Edit</button><button class="danger" onclick="deletePopular(${c.id})">Delete</button></div></div>`).join('') || '<p>No cards.</p>'; }
window.editPopular = id => { const c=(state.siteContent.popular_help||[]).find(x=>x.id===id); if(!c)return; $('popularFormTitle').textContent='Edit Popular Help Card'; $('popularId').value=c.id; $('popularTitleInput').value=c.title; $('popularSubtitle').value=c.subtitle; $('popularIcon').value=c.icon; $('popularQuery').value=c.query; $('popularCategorySlug').value=c.linked_category_slug; $('popularSort').value=c.sort_order; $('popularStatus').value=c.status; };
window.deletePopular = id => safe(async()=>{ if(!confirm('Delete this card?'))return; await api(`/admin/popular-help/${id}`,{method:'DELETE'}); toast('Card deleted'); await loadSiteContent(); });
$('resetPopular').addEventListener('click',()=>{$('popularForm').reset();$('popularId').value='';$('popularIcon').value='✨';$('popularSort').value=100;$('popularStatus').value='active';$('popularFormTitle').textContent='Popular Help Card';});
$('popularForm').addEventListener('submit', e => safe(async()=>{ e.preventDefault(); const id=$('popularId').value; const body=JSON.stringify({title:$('popularTitleInput').value,subtitle:$('popularSubtitle').value,icon:$('popularIcon').value,query:$('popularQuery').value,linked_category_slug:$('popularCategorySlug').value,sort_order:numberVal('popularSort'),status:$('popularStatus').value}); await api(id?`/admin/popular-help/${id}`:'/admin/popular-help',{method:id?'PUT':'POST',body}); toast('Popular card saved'); $('resetPopular').click(); await loadSiteContent(); }));
function renderNavigation() { $('navList').innerHTML = (state.siteContent.navigation || []).map(n => `<div class="item slim"><div><h3>${esc(n.icon)} ${esc(n.label)}</h3><span class="badge">${esc(n.nav_key)} · ${esc(n.status)} · ${esc(n.href)}</span></div><div class="mini-actions"><button onclick="editNav(${n.id})">Edit</button><button class="danger" onclick="deleteNav(${n.id})">Delete</button></div></div>`).join('') || '<p>No navigation.</p>'; }
window.editNav = id => { const n=(state.siteContent.navigation||[]).find(x=>x.id===id); if(!n)return; $('navFormTitle').textContent='Edit Bottom Navigation'; $('navId').value=n.id; $('navKey').value=n.nav_key; $('navLabel').value=n.label; $('navIcon').value=n.icon; $('navHref').value=n.href; $('navSort').value=n.sort_order; $('navStatus').value=n.status; };
window.deleteNav = id => safe(async()=>{ if(!confirm('Delete nav item?'))return; await api(`/admin/navigation/${id}`,{method:'DELETE'}); toast('Nav deleted'); await loadSiteContent(); });
$('resetNav').addEventListener('click',()=>{$('navForm').reset();$('navId').value='';$('navIcon').value='•';$('navSort').value=100;$('navStatus').value='active';$('navFormTitle').textContent='Bottom Navigation';});
$('navForm').addEventListener('submit', e => safe(async()=>{ e.preventDefault(); const id=$('navId').value; const body=JSON.stringify({nav_key:$('navKey').value,label:$('navLabel').value,icon:$('navIcon').value,href:$('navHref').value,sort_order:numberVal('navSort'),status:$('navStatus').value}); await api(id?`/admin/navigation/${id}`:'/admin/navigation',{method:id?'PUT':'POST',body}); toast('Navigation saved'); $('resetNav').click(); await loadSiteContent(); }));
function renderQuick() { $('quickList').innerHTML = (state.siteContent.chat_quick_replies || []).map(q => `<div class="item slim"><div><h3>${esc(q.text)}</h3><span class="badge">${esc(q.status)} · ${esc(q.query)}</span></div><div class="mini-actions"><button onclick="editQuick(${q.id})">Edit</button><button class="danger" onclick="deleteQuick(${q.id})">Delete</button></div></div>`).join('') || '<p>No quick replies.</p>'; }
window.editQuick = id => { const q=(state.siteContent.chat_quick_replies||[]).find(x=>x.id===id); if(!q)return; $('quickFormTitle').textContent='Edit Chat Quick Reply'; $('quickId').value=q.id; $('quickText').value=q.text; $('quickQuery').value=q.query; $('quickSort').value=q.sort_order; $('quickStatus').value=q.status; };
window.deleteQuick = id => safe(async()=>{ if(!confirm('Delete quick reply?'))return; await api(`/admin/chat-quick-replies/${id}`,{method:'DELETE'}); toast('Quick reply deleted'); await loadSiteContent(); });
$('resetQuick').addEventListener('click',()=>{$('quickForm').reset();$('quickId').value='';$('quickSort').value=100;$('quickStatus').value='active';$('quickFormTitle').textContent='Chat Quick Reply';});
$('quickForm').addEventListener('submit', e => safe(async()=>{ e.preventDefault(); const id=$('quickId').value; const body=JSON.stringify({text:$('quickText').value,query:$('quickQuery').value,sort_order:numberVal('quickSort'),status:$('quickStatus').value}); await api(id?`/admin/chat-quick-replies/${id}`:'/admin/chat-quick-replies',{method:id?'PUT':'POST',body}); toast('Quick reply saved'); $('resetQuick').click(); await loadSiteContent(); }));

async function loadCategories() { state.categories = await api('/admin/categories'); $('guideCategory').innerHTML = '<option value="">No category</option>' + state.categories.map(c => `<option value="${c.id}">${esc(c.icon||'🎯')} ${esc(c.name)}</option>`).join(''); $('categoryList').innerHTML = state.categories.map(c => `<div class="item"><div class="item-head"><div><h3>${esc(c.icon||'🎯')} ${esc(c.name)}</h3><span class="badge">/${esc(c.slug)} · order ${esc(c.sort_order)}</span></div></div><p>${esc(c.description||'')}</p><div class="mini-actions"><button onclick="editCategory(${c.id})">Edit</button><button class="danger" onclick="deleteCategory(${c.id})">Delete</button></div></div>`).join('') || '<p>No categories yet.</p>'; }
window.editCategory = id => { const c=state.categories.find(x=>x.id===id); if(!c)return; $('categoryFormTitle').textContent='Edit category'; $('categoryId').value=c.id; $('categoryName').value=c.name; $('categorySlug').value=c.slug; $('categoryIcon').value=c.icon||'🎯'; $('categorySort').value=c.sort_order||100; $('categoryDescription').value=c.description||''; };
window.deleteCategory = id => safe(async()=>{ if(!confirm('Delete this category?'))return; await api(`/admin/categories/${id}`,{method:'DELETE'}); toast('Category deleted'); await loadCategories(); });
$('resetCategory').addEventListener('click',()=>{$('categoryForm').reset();$('categoryId').value='';$('categoryIcon').value='🎯';$('categorySort').value=100;$('categoryFormTitle').textContent='Create category';});
$('categoryForm').addEventListener('submit', e => safe(async()=>{ e.preventDefault(); const id=$('categoryId').value; const body=JSON.stringify({name:$('categoryName').value,slug:$('categorySlug').value||null,description:$('categoryDescription').value,icon:$('categoryIcon').value||'🎯',sort_order:numberVal('categorySort')}); await api(id?`/admin/categories/${id}`:'/admin/categories',{method:id?'PUT':'POST',body}); toast('Category saved'); $('resetCategory').click(); await loadCategories(); }));

function renderGuidePreview(){ $('guidePreview').innerHTML = lines($('guideImages').value).map(url=>`<img src="${esc(url)}" alt="preview"/>`).join(''); }
$('guideImages').addEventListener('input',renderGuidePreview);
$('uploadGuideImage').addEventListener('click',()=>safe(async()=>{ const file=$('guideImageFile').files?.[0]; if(!file)return toast('Choose an image first'); const data=new FormData(); data.append('file',file); const res=await api('/admin/uploads',{method:'POST',body:data}); $('guideImages').value=[...lines($('guideImages').value),res.url].join('\n'); $('guideImageFile').value=''; renderGuidePreview(); toast('Image uploaded'); }));
async function loadGuides(){ state.guides=await api('/admin/guides'); $('guideList').innerHTML=state.guides.map(g=>`<div class="item"><div class="item-head"><div><h3>${esc(g.title)}</h3><span class="badge">${esc(g.status)} · ${esc(g.category_name||'No category')} · priority ${esc(g.priority)}</span></div></div>${g.image_urls?.[0]?`<img class="item-img" src="${esc(g.image_urls[0])}" alt="${esc(g.title)}"/>`:''}<p>${esc(g.summary||'')}</p><small><b>Keywords:</b> ${esc(g.keywords||'-')}</small><div class="mini-actions"><button onclick="editGuide(${g.id})">Edit</button><button class="danger" onclick="deleteGuide(${g.id})">Delete</button></div></div>`).join('')||'<p>No guides yet.</p>'; }
window.editGuide=id=>{const g=state.guides.find(x=>x.id===id); if(!g)return; $('guideFormTitle').textContent='Edit smart guide'; $('guideId').value=g.id; $('guideTitle').value=g.title; $('guideSlug').value=g.slug; $('guideCategory').value=g.category_id||''; $('guidePriority').value=g.priority||100; $('guideLanguage').value=g.language||'en'; $('guideSummary').value=g.summary||''; $('guideBody').value=g.body||''; $('guideKeywords').value=g.keywords||''; $('guideImages').value=(g.image_urls||[]).join('\n'); $('guideStatus').value=g.status||'published'; renderGuidePreview();};
window.deleteGuide=id=>safe(async()=>{if(!confirm('Delete this guide?'))return; await api(`/admin/guides/${id}`,{method:'DELETE'}); toast('Guide deleted'); await loadGuides();});
$('resetGuide').addEventListener('click',()=>{$('guideForm').reset();$('guideId').value='';$('guidePriority').value=100;$('guideLanguage').value='en';$('guideStatus').value='published';$('guideFormTitle').textContent='Create smart guide';renderGuidePreview();});
$('guideForm').addEventListener('submit',e=>safe(async()=>{e.preventDefault(); const id=$('guideId').value; const body=JSON.stringify({title:$('guideTitle').value,slug:$('guideSlug').value||null,category_id:$('guideCategory').value?Number($('guideCategory').value):null,summary:$('guideSummary').value,body:$('guideBody').value,image_urls:lines($('guideImages').value),keywords:$('guideKeywords').value,language:$('guideLanguage').value||'en',priority:numberVal('guidePriority'),status:$('guideStatus').value}); await api(id?`/admin/guides/${id}`:'/admin/guides',{method:id?'PUT':'POST',body}); toast('Guide saved'); $('resetGuide').click(); await loadGuides();}));

async function loadFaqs(){ state.faqs=await api('/admin/faqs'); $('faqList').innerHTML=state.faqs.map(f=>`<div class="item"><h3>${esc(f.question)}</h3><span class="badge">${esc(f.status)} · priority ${esc(f.priority)}</span><p>${esc(f.answer)}</p><small><b>Keywords:</b> ${esc(f.keywords||'-')}</small><div class="mini-actions"><button onclick="editFaq(${f.id})">Edit</button><button class="danger" onclick="deleteFaq(${f.id})">Delete</button></div></div>`).join('')||'<p>No FAQs yet.</p>'; }
window.editFaq=id=>{const f=state.faqs.find(x=>x.id===id); if(!f)return; $('faqFormTitle').textContent='Edit FAQ'; $('faqId').value=f.id; $('faqQuestion').value=f.question; $('faqAnswer').value=f.answer; $('faqKeywords').value=f.keywords||''; $('faqPriority').value=f.priority||100; $('faqStatus').value=f.status||'published';};
window.deleteFaq=id=>safe(async()=>{if(!confirm('Delete this FAQ?'))return; await api(`/admin/faqs/${id}`,{method:'DELETE'}); toast('FAQ deleted'); await loadFaqs();});
$('resetFaq').addEventListener('click',()=>{$('faqForm').reset();$('faqId').value='';$('faqPriority').value=100;$('faqStatus').value='published';$('faqFormTitle').textContent='Create FAQ';});
$('faqForm').addEventListener('submit',e=>safe(async()=>{e.preventDefault(); const id=$('faqId').value; const body=JSON.stringify({question:$('faqQuestion').value,answer:$('faqAnswer').value,keywords:$('faqKeywords').value,priority:numberVal('faqPriority'),status:$('faqStatus').value}); await api(id?`/admin/faqs/${id}`:'/admin/faqs',{method:id?'PUT':'POST',body}); toast('FAQ saved'); $('resetFaq').click(); await loadFaqs();}));

async function loadKnowledge(){ state.knowledge=await api('/admin/knowledge'); $('knowledgeList').innerHTML=state.knowledge.map(k=>`<div class="item"><h3>${esc(k.title)}</h3><span class="badge">${esc(k.status)} · priority ${esc(k.priority)}</span><p>${esc(k.content)}</p><small><b>Keywords:</b> ${esc(k.keywords||'-')}</small><div class="mini-actions"><button onclick="editKnowledge(${k.id})">Edit</button><button class="danger" onclick="deleteKnowledge(${k.id})">Delete</button></div></div>`).join('')||'<p>No knowledge yet.</p>'; }
window.editKnowledge=id=>{const k=state.knowledge.find(x=>x.id===id); if(!k)return; $('knowledgeFormTitle').textContent='Edit knowledge'; $('knowledgeId').value=k.id; $('knowledgeTitle').value=k.title; $('knowledgeContent').value=k.content; $('knowledgeKeywords').value=k.keywords||''; $('knowledgePriority').value=k.priority||100; $('knowledgeStatus').value=k.status||'active';};
window.deleteKnowledge=id=>safe(async()=>{if(!confirm('Delete this knowledge item?'))return; await api(`/admin/knowledge/${id}`,{method:'DELETE'}); toast('Knowledge deleted'); await loadKnowledge();});
$('resetKnowledge').addEventListener('click',()=>{$('knowledgeForm').reset();$('knowledgeId').value='';$('knowledgePriority').value=100;$('knowledgeStatus').value='active';$('knowledgeFormTitle').textContent='Create knowledge';});
$('knowledgeForm').addEventListener('submit',e=>safe(async()=>{e.preventDefault(); const id=$('knowledgeId').value; const body=JSON.stringify({title:$('knowledgeTitle').value,content:$('knowledgeContent').value,keywords:$('knowledgeKeywords').value,priority:numberVal('knowledgePriority'),status:$('knowledgeStatus').value}); await api(id?`/admin/knowledge/${id}`:'/admin/knowledge',{method:id?'PUT':'POST',body}); toast('Knowledge saved'); $('resetKnowledge').click(); await loadKnowledge();}));

async function loadAiMode(){ await Promise.allSettled([loadAiSettings(),loadAiPrompts(),loadPromptVersions(),loadSessions()]); }
async function loadAiSettings(){ state.aiSettings=await api('/admin/ai/settings'); const a=state.aiSettings; $('aiProvider').value=a.provider||'deepseek'; $('aiModel').value=a.model||'deepseek-chat'; $('aiApiBase').value=a.api_base||'https://api.deepseek.com'; $('aiEnabled').checked=!!a.enabled; $('aiTemperature').value=a.temperature??0.2; $('aiMaxTokens').value=a.max_tokens??700; $('aiRequireContext').checked=!!a.require_approved_context; $('aiMemoryEnabled').checked=!!a.memory_enabled; $('aiMemoryMax').value=a.memory_max_messages??12; $('aiMemoryTtl').value=a.memory_ttl_days??30; $('aiKeyStatus').innerHTML=a.has_api_key?'<span class="ok">DeepSeek API key detected.</span>':'<span class="warn">No DEEPSEEK_API_KEY detected.</span>'; }
$('aiSettingsForm').addEventListener('submit',e=>safe(async()=>{e.preventDefault(); const body=JSON.stringify({provider:$('aiProvider').value,model:$('aiModel').value,api_base:$('aiApiBase').value,enabled:$('aiEnabled').checked,temperature:Number($('aiTemperature').value||0.2),max_tokens:Number($('aiMaxTokens').value||700),require_approved_context:$('aiRequireContext').checked,memory_enabled:$('aiMemoryEnabled').checked,memory_max_messages:Number($('aiMemoryMax').value||12),memory_ttl_days:Number($('aiMemoryTtl').value||30)}); await api('/admin/ai/settings',{method:'PUT',body}); toast('AI settings saved'); await loadAiSettings(); }));
async function loadAiPrompts(){ state.aiPrompts=await api('/admin/ai/prompts'); $('aiPromptList').innerHTML=state.aiPrompts.map(p=>`<div class="item"><div class="item-head"><div><h3>${esc(p.title)}</h3><span class="badge">${esc(p.section_key)} · ${p.enabled?'enabled':'disabled'} · priority ${esc(p.priority)}</span></div></div><p>${esc(p.content)}</p><div class="mini-actions"><button onclick="editAiPrompt(${p.id})">Edit</button><button onclick="filterPromptVersions(${p.id})">Versions</button><button class="danger" onclick="deleteAiPrompt(${p.id})">Delete</button></div></div>`).join('')||'<p>No prompt sections yet.</p>'; }
window.editAiPrompt=id=>{const p=state.aiPrompts.find(x=>x.id===id); if(!p)return; $('aiPromptFormTitle').textContent='Edit prompt section'; $('aiPromptId').value=p.id; $('aiPromptKey').value=p.section_key; $('aiPromptTitle').value=p.title; $('aiPromptContent').value=p.content||''; $('aiPromptPriority').value=p.priority||100; $('aiPromptEnabled').value=String(!!p.enabled);};
window.deleteAiPrompt=id=>safe(async()=>{if(!confirm('Delete prompt section?'))return; await api(`/admin/ai/prompts/${id}`,{method:'DELETE'}); toast('Prompt deleted'); await loadAiMode();});
window.filterPromptVersions=id=>safe(async()=>{ state.promptVersions=await api(`/admin/ai/prompts/${id}/versions`); renderPromptVersions(); });
$('resetAiPrompt').addEventListener('click',()=>{$('aiPromptForm').reset();$('aiPromptId').value='';$('aiPromptEnabled').value='true';$('aiPromptPriority').value=100;$('aiPromptFormTitle').textContent='Prompt Section';});
$('aiPromptForm').addEventListener('submit',e=>safe(async()=>{e.preventDefault(); const id=$('aiPromptId').value; const body=JSON.stringify({section_key:$('aiPromptKey').value,title:$('aiPromptTitle').value||$('aiPromptKey').value,content:$('aiPromptContent').value,enabled:bool($('aiPromptEnabled').value),priority:numberVal('aiPromptPriority')}); await api(id?`/admin/ai/prompts/${id}`:'/admin/ai/prompts',{method:id?'PUT':'POST',body}); toast('Prompt saved with version history'); $('resetAiPrompt').click(); await loadAiMode();}));
async function loadPromptVersions(){ state.promptVersions=await api('/admin/ai/prompt-versions'); renderPromptVersions(); }
function renderPromptVersions(){ $('promptVersionList').innerHTML=state.promptVersions.map(v=>`<div class="item slim"><div><h3>${esc(v.title||v.section_key)}</h3><span class="badge">${esc(v.change_note||'saved')} · ${esc(v.created_at)}</span><p>${esc((v.content||'').slice(0,220))}</p></div><button onclick="restorePrompt(${v.prompt_id},${v.id})">Restore</button></div>`).join('')||'<p>No prompt versions yet.</p>'; }
window.restorePrompt=(pid,vid)=>safe(async()=>{ if(!confirm('Restore this prompt version?'))return; await api(`/admin/ai/prompts/${pid}/restore/${vid}`,{method:'POST'}); toast('Prompt restored'); await loadAiMode(); });
$('aiTestForm').addEventListener('submit',e=>safe(async()=>{e.preventDefault(); $('aiTestResult').innerHTML='Testing...'; const res=await api('/admin/ai/test',{method:'POST',body:JSON.stringify({message:$('aiTestMessage').value,session_id:$('aiTestSession').value||'admin-test',image_urls:lines($('aiTestImages').value)})}); $('aiTestResult').innerHTML=`<b>Reply</b><p>${esc(res.reply)}</p><small>Model: ${esc(res.model)} · DeepSeek: ${res.used_deepseek?'yes':'no'}${res.deepseek_error?` · ${esc(res.deepseek_error)}`:''}</small><pre>${esc(JSON.stringify(res.diagnostics||{},null,2))}</pre>`; }));
$('loadDiagnosticsBtn').addEventListener('click',()=>safe(loadDiagnostics));
async function loadDiagnostics(){ const d=await api('/admin/ai/diagnostics'); $('diagnosticsBox').innerHTML=`<pre>${esc(JSON.stringify(d,null,2))}</pre>`; return d; }
async function loadSessions(){ state.sessions=await api('/admin/chat-sessions'); $('sessionList').innerHTML=state.sessions.map(s=>`<div class="item"><h3>${esc(s.session_id)}</h3><p>${esc(s.memory_summary||'No memory yet.')}</p><span class="badge">messages ${esc(s.message_count)} · ${esc(s.updated_at)}</span><div class="mini-actions"><button class="danger" onclick="clearSession('${esc(s.session_id)}')">Clear Memory</button></div></div>`).join('')||'<p>No sessions yet.</p>'; }
window.clearSession=sid=>safe(async()=>{ await api(`/admin/chat-sessions/${encodeURIComponent(sid)}`,{method:'DELETE'}); toast('Memory cleared'); await loadSessions(); });
async function loadLogs(){ state.logs=await api('/admin/chat-logs'); $('logList').innerHTML=state.logs.map(l=>`<div class="item"><h3>${esc(l.customer_message)}</h3><p>${esc(l.assistant_reply)}</p><span class="badge">${esc(l.model)} · ${esc(l.created_at)}</span></div>`).join('')||'<p>No chat logs yet.</p>'; }
async function loadAudit(){ state.audit=await api('/admin/audit-logs'); $('auditList').innerHTML=state.audit.map(a=>`<div class="item slim"><div><h3>${esc(a.action)} · ${esc(a.entity_type||'')}</h3><span class="badge">${esc(a.entity_id||'')} · ${esc(a.created_at)}</span><p>${esc(a.details||'')}</p></div></div>`).join('')||'<p>No audit logs yet.</p>'; }

if (state.token) showApp(); else showLogin();
