import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const checks = [];
const expect = (name, condition) => checks.push({ name, ok: Boolean(condition) });

const core = read("backend-api/src/core.js");
const server = read("backend-api/src/server.js");
const env = read("backend-api/src/env.js");
const adminLayout = read("admin-pro/src/components/AdminLayout.tsx");
const domainPage = read("admin-pro/src/routes/_admin.domain-mapping.tsx");
const guidePage = read("admin-pro/src/routes/_admin.guide-images.tsx");
const adminApi = read("admin-pro/src/lib/api.ts");
const guidePublicPage = read("guide-pro/src/routes/_public.guides.$slug.tsx");
const guidePublicApi = read("guide-pro/src/lib/api.ts");
const r2Adapter = read("backend-api/src/r2-adapter.js");
const publishingMigration = read("backend-api/migrations/031_v1.14.3_guide_publishing_state_repair_platform_self_service_upload.sql");
const migration = read("backend-api/migrations/032_v1.15.0_advanced_visual_guide_studio_motion_media.sql");

expect("Backend and server expose the v1.15.0 release", core.includes("1.15.0-advanced-visual-guide-studio-motion-media") && server.includes("1.15.0-advanced-visual-guide-studio-motion-media"));
expect("Domain route IDs are extracted from the numeric path segment", core.includes("function domainIdFromPath") && core.includes("Number.isSafeInteger(id)") && core.includes("DOMAIN_ID_INVALID"));
expect("Provision uses the validated domain ID", core.includes("provisionMappedDomain(env, domainIdFromPath(path), scope)") && !core.includes("provisionMappedDomain(env, idFromParts(path, 3), scope)"));
expect("Sync, verify, and delete use the validated domain ID", ["syncMappedDomain(env, domainIdFromPath(path), scope)", "verifyMappedDomain(env, domainIdFromPath(path), scope)", "deleteMappedDomain(env, domainIdFromPath(path), scope)"].every((item) => core.includes(item)));
expect("Invalid domain IDs return a client error before SQL", core.includes("DOMAIN_ID_INVALID") && core.includes("The domain mapping ID is invalid."));
expect("Cloudflare configuration status is safe and non-secret", core.includes("function cloudflareConfigurationStatus") && core.includes("required_env") && core.includes("missing_env") && !core.includes("api_token: config.api_token"));
expect("Cloudflare provisioning has a clear 503 guard", core.includes("CLOUDFLARE_NOT_CONFIGURED") && core.includes("Missing Render variables") && core.includes("503"));
expect("Domain mapping exposes missing configuration names", core.includes("const cloudflare = { ...cloudflareConfigurationStatus(env)") && core.includes("cloudflare.missing_env.join"));
expect("Render environment validation covers Cloudflare prerequisites", env.includes("CLOUDFLARE_CUSTOM_HOSTNAMES_ENABLED") && env.includes("CLOUDFLARE_API_TOKEN") && env.includes("CLOUDFLARE_ZONE_ID") && env.includes("CLOUDFLARE_SAAS_CNAME_TARGET"));
expect("Admin disables Provision until Cloudflare is configured", domainPage.includes("const cloudflareReady = data?.cloudflare?.configured === true") && domainPage.includes("disabled={!cloudflareReady}"));
expect("Admin displays the exact missing Render variables", domainPage.includes("data?.cloudflare?.missing_env") && domainPage.includes("Set these Render variables before provisioning"));
expect("Admin release marker is v1.15.0", adminLayout.includes('const ADMIN_VERSION = "v1.15.0"'));
expect("v1.14.1 single-image contract remains present", core.includes("const legacyContentImages = imageDelivery.image_count ? [] : contentImages") && core.includes("A response without procedural steps has one canonical visual at most"));
expect("Platform context remains strict with no fallback", core.includes("PLATFORM_CONTEXT_REQUIRED") && core.includes("fallback_applied: false") && !core.includes("publicReference || 'default'"));
expect("v1.14.3 migration repairs existing parent Guide drafts", publishingMigration.includes("UPDATE guides g") && publishingMigration.includes("gt.status = 'published'"));
expect("Guide publish activates the translation and parent atomically", core.includes("WITH published AS (") && core.includes("UPDATE guides g SET status='published'"));
expect("Batch publish activates every affected parent Guide", core.includes("guides_activated") && core.includes("SELECT DISTINCT guide_id FROM published"));
expect("Guide reads expose derived publication state", core.includes("publication_status") && core.includes("published_locale_count") && core.includes("enabled_locale_count"));
expect("A draft default-locale translation cannot leak through the legacy parent row", core.includes("const hasLocaleRow") && core.includes("if (!hasLocaleRow)") && core.includes("GUIDE_TRANSLATION_UNAVAILABLE"));
expect("Saving legacy Guide fields cannot silently demote a published locale", core.includes("cover_image_url=EXCLUDED.cover_image_url,keywords=EXCLUDED.keywords,updated_at=NOW()"));
expect("Guide owner permissions are enforced by the backend", core.includes("GUIDE_UPLOAD_DENIED") && core.includes("GUIDE_PUBLISH_DENIED") && core.includes("requireGuidePublish(scope)"));
expect("Guide UI reads platform upload and publish capabilities", guidePage.includes("can_upload_guides") && guidePage.includes("can_publish_guides"));
expect("Guide UI uses the dedicated self-service upload route", adminApi.includes('uploadAdminFile(file, "/admin/guide-uploads")') && guidePage.includes("api.uploadGuide(file)"));
expect("Guide media keys are tenant and platform scoped", core.includes("tenant-${Number(scope.tenant_id)}/platform-${Number(scope.platform_id)}"));
expect("Guide upload validates image signatures", core.includes("detectImageContentType") && core.includes("UPLOAD_CONTENT_SIGNATURE_MISMATCH"));
expect("Guide media ownership and audit records are durable", publishingMigration.includes("guide_media_assets") && core.includes("Guide ${mediaKind} uploaded"));
expect("v1.15.0 migration adds locale-scoped cover media and motion settings", ["cover_media_type", "cover_video_url", "video_autoplay", "motion_enabled", "title_animation", "content_animation"].every((field) => migration.includes(field)));
expect("Motion media has a dedicated platform-guarded upload route", core.includes("/admin/guide-motion-uploads") && core.includes("allowMotionMedia:true") && adminApi.includes('uploadAdminFile(file, "/admin/guide-motion-uploads")'));
expect("Guide motion uploads allow only verified GIF, MP4, and WebM media", core.includes("detectGuideMediaContentType") && core.includes("video/mp4") && core.includes("video/webm") && core.includes("String.fromCharCode(...bytes.slice(4, 8)) === 'ftyp'"));
expect("Autoplay video is normalized to muted", core.includes("const muted = autoplay ? true") && core.includes("videoAutoplay ? true"));
expect("Admin exposes cover type, autoplay, loop, poster, and safe text motion controls", ["cover_media_type", "video_autoplay", "video_loop", "cover_video_poster_url", "title_animation", "summary_animation", "content_animation"].every((field) => guidePage.includes(field)));
expect("Public Guide renders video and animated GIF-compatible images", guidePublicPage.includes("<video") && guidePublicPage.includes("coverMedia?.type === \"video\"") && guidePublicApi.includes("coverMediaType === \"video\""));
expect("Public Guide honors reduced-motion preferences", guidePublicPage.includes("prefers-reduced-motion: reduce") && guidePublicPage.includes("useReducedMotion") && guidePublicPage.includes("!prefersReducedMotion"));
expect("Only allowlisted motion presets reach the renderer", core.includes("GUIDE_ANIMATION_PRESETS") && guidePublicPage.includes("SAFE_MOTION_PRESETS"));
expect("R2 media delivery supports HTTP byte ranges", r2Adapter.includes("supportsHttpRange: true") && r2Adapter.includes("Range: range") && core.includes("'Content-Range'"));

for (const check of checks) console.log(`${check.ok ? "PASS" : "FAIL"} ${check.name}`);
const failed = checks.filter((check) => !check.ok);
console.log(`\n${checks.length - failed.length}/${checks.length} v1.15.0 regression checks passed`);
if (failed.length) process.exitCode = 1;
