import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const checks = [];
const expect = (name, condition) => checks.push({ name, ok: Boolean(condition) });

const core = read("backend-api/src/core.js");
const server = read("backend-api/src/server.js");
const env = read("backend-api/src/env.js");
const importer = read("backend-api/src/knowledge-import.js");
const migration = read("backend-api/migrations/028_v1.13.0_bring_your_own_domain_cloudflare_custom_hostnames.sql");
const adminApi = read("admin-pro/src/lib/api.ts");
const adminLayout = read("admin-pro/src/components/AdminLayout.tsx");
const importPage = read("admin-pro/src/routes/_admin.ai-knowledge-import.tsx");
const qaPage = read("admin-pro/src/routes/_admin.ai-qa.tsx");
const routerPage = read("admin-pro/src/routes/_admin.ai-source-router.tsx");
const localizedHelp = read("admin-pro/src/components/LocalizedHelp.tsx");
const domainPage = read("admin-pro/src/routes/_admin.domain-mapping.tsx");
const reliabilityPage = read("admin-pro/src/routes/_admin.ai-reliability.tsx");

expect("Backend and server expose the same v1.13.0 release", core.includes("1.13.0-bring-your-own-domain-cloudflare-custom-hostnames") && server.includes("1.13.0-bring-your-own-domain-cloudflare-custom-hostnames"));
expect("Backend source remains assembled", core.includes("async function ensureBootstrap") && server.includes("createServer"));
expect("Workbook parser requires Question and Answer", importer.includes("Could not find both Question and How to reply / Answer columns."));
expect("Workbook parser accepts the named Name column", importer.includes("name: ['name'") && importer.includes("content_name: name"));
expect("Workbook parser supports image roles and placement", importer.includes("image_role") && importer.includes("image_placement") && importer.includes("image_urls"));
expect("Named import template is downloadable", core.includes("knowledgeImportTemplateResponse") && core.includes("['Name','Question','How to reply / Answer'"));
expect("v1.13.0 migration is additive and idempotent", migration.includes("ADD COLUMN IF NOT EXISTS") && migration.includes("CREATE INDEX IF NOT EXISTS") && migration.includes("ON CONFLICT (migration_key) DO NOTHING"));
expect("Cloudflare runtime settings are backend-only and validated", env.includes("CLOUDFLARE_API_TOKEN") && env.includes("CLOUDFLARE_ZONE_ID") && env.includes("CLOUDFLARE_SAAS_CNAME_TARGET") && env.includes("CLOUDFLARE_CUSTOM_HOSTNAME_VALIDATION_METHOD") && env.includes("CLOUDFLARE_CUSTOM_HOSTNAME_ORIGIN_CHAT"));
expect("Cloudflare Custom Hostname API uses the zone endpoint", core.includes("api.cloudflare.com/client/v4/zones") && core.includes("/custom_hostnames") && core.includes("Authorization: `Bearer ${config.api_token}`"));
expect("Cloudflare ownership and SSL records are returned safely", core.includes("ownership_verification") && core.includes("ssl_validation_records") && core.includes("cloudflareValidationRecords"));
expect("Hostname and SSL readiness are separate", core.includes("hostnameStatus === 'active' && sslStatus === 'active'") && core.includes("provisioning_status: 'pending_ssl'") && core.includes("cloudflare_ssl_status"));
expect("Domain DNS instructions include TXT and CNAME records", core.includes("Cloudflare hostname ownership verification") && core.includes("Cloudflare certificate validation") && core.includes("Route customer traffic to the SaaS zone"));
expect("Domain mapping is tenant-scoped through the platform join", core.includes("JOIN saas_platforms p ON p.id=d.platform_id") && core.includes("p.tenant_id=$1::integer") && !core.includes("FROM saas_platform_domains WHERE tenant_id"));
expect("Domain lifecycle routes support add, provision, sync, verify, and archive", ["/admin/domain-mapping/domains", "/provision", "/sync", "/verify", "deleteMappedDomain"].every((item) => core.includes(item)));
expect("Custom hostnames resolve to the owning platform", core.includes("source === 'hostname'") && core.includes("CUSTOM_HOSTNAME_NOT_READY") && core.includes("lower(d.hostname)=lower($1)"));
expect("Custom hostname URLs remain route-aware", core.includes("origin_hostname") && core.includes("PLATFORM_CONTEXT_MISMATCH") && core.includes("customHostnameFromRequest"));
expect("Dynamic custom-hostname CORS is explicit", server.includes("isActiveCustomHostnameOrigin") && core.includes("X-BDG-Platform-Host"));
expect("Missing and malformed context are rejected", core.includes("PLATFORM_CONTEXT_REQUIRED") && core.includes("PLATFORM_CONTEXT_INVALID") && core.includes("PLATFORM_NOT_FOUND"));
expect("Public context never silently defaults to BDG", core.includes("const publicReference = publicContext.reference || publicContext.raw_reference || ''") && !core.includes("resolvePublicPlatformScope(env, publicReference || 'default')"));
expect("Admin AI tests use the active SaaS platform scope", core.includes("testAiContent(env, await readJson(request), scope)") && core.includes("runAiChat(env, await readJson(request), true, scope, scope.platform_context)") && !core.includes("testAiContent(env, await readJson(request), scope.legacy_support_platform_key"));
expect("Chat accepts JSON platform_key and preserves origin context", core.includes("function platformContextFromPayload") && core.includes("const chatReference = chatContext.reference || chatContext.raw_reference || ''") && core.includes("origin_hostname"));
expect("AI source routing remains platform and locale scoped", core.includes("tenant_id=$1::integer AND platform_id=$2::integer") && core.includes("published_only: true") && core.includes("tenant_platform_scoped: true"));
expect("AI reliability diagnostics remain platform-scoped", core.includes("ai_reliability_settings") && core.includes("failure_stage") && core.includes("testAiReliability"));
expect("Admin API exposes BYOD lifecycle controls", ["createDomainMappingDomain", "provisionMappedDomain", "syncMappedDomain", "deleteMappedDomain"].every((item) => adminApi.includes(item)));
expect("Admin domain screen explains BYOD in three languages", domainPage.includes("Bring Your Own Domain") && domainPage.includes("客户自己向域名注册商购买域名") && domainPage.includes("ဖောက်သည်သည် domain"));
expect("Admin domain screen displays DNS records and readiness", domainPage.includes("DNS records to add at the customer DNS provider") && domainPage.includes("SSL") && domainPage.includes("Provision"));
expect("Admin Q&A and import controls remain present", qaPage.includes("Search name, question, intent") && importPage.includes("Download template") && importPage.includes("Publish batch"));
expect("Admin router can pause sources without deleting content", routerPage.includes("Enabled sources") && routerPage.includes("Removing a source pauses it"));
expect("Admin help system supports English, Chinese, and Burmese", localizedHelp.includes("zh") && localizedHelp.includes("my") && importPage.includes("LocalizedHelp") && qaPage.includes("LocalizedHelp") && routerPage.includes("LocalizedHelp"));
expect("Admin release marker is v1.13.0", adminLayout.includes('const ADMIN_VERSION = "v1.13.0"'));
expect("v1.13.0 bootstrap marker is idempotent", core.includes("v1.13.0_bring_your_own_domain_cloudflare_custom_hostnames") && core.includes("ON CONFLICT(migration_key) DO NOTHING"));

for (const check of checks) console.log(`${check.ok ? "PASS" : "FAIL"} ${check.name}`);
const failed = checks.filter((check) => !check.ok);
console.log(`\n${checks.length - failed.length}/${checks.length} v1.13.0 regression checks passed`);
if (failed.length) process.exitCode = 1;
