/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminVersionsRouteImport } from './routes/admin.versions'
import { Route as AdminSiteContentRouteImport } from './routes/admin.site-content'
import { Route as AdminPopularHelpRouteImport } from './routes/admin.popular-help'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGuidesRouteImport } from './routes/admin.guides'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as PublicSupportRouteImport } from './routes/_public.support'
import { Route as PublicGuidesRouteImport } from './routes/_public.guides'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as AdminGuidesNewRouteImport } from './routes/admin.guides.new'
import { Route as AdminGuidesIdRouteImport } from './routes/admin.guides.$id'
import { Route as PublicGuidesSlugRouteImport } from './routes/_public.guides.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminVersionsRoute = AdminVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopularHelpRoute = AdminPopularHelpRouteImport.update({
  id: '/popular-help',
  path: '/popular-help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const PublicSupportRoute = PublicSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGuidesRoute = PublicGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const AdminGuidesNewRoute = AdminGuidesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminGuidesRoute,
} as any)
const AdminGuidesIdRoute = AdminGuidesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminGuidesRoute,
} as any)
const PublicGuidesSlugRoute = PublicGuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicGuidesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof PublicFaqRoute
  '/guides': typeof PublicGuidesRouteWithChildren
  '/support': typeof PublicSupportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/guides': typeof AdminGuidesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/popular-help': typeof AdminPopularHelpRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/$slug': typeof PublicGuidesSlugRoute
  '/admin/guides/$id': typeof AdminGuidesIdRoute
  '/admin/guides/new': typeof AdminGuidesNewRoute
}
export interface FileRoutesByTo {
  '/faq': typeof PublicFaqRoute
  '/guides': typeof PublicGuidesRouteWithChildren
  '/support': typeof PublicSupportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/guides': typeof AdminGuidesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/popular-help': typeof AdminPopularHelpRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/guides/$slug': typeof PublicGuidesSlugRoute
  '/admin/guides/$id': typeof AdminGuidesIdRoute
  '/admin/guides/new': typeof AdminGuidesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/faq': typeof PublicFaqRoute
  '/_public/guides': typeof PublicGuidesRouteWithChildren
  '/_public/support': typeof PublicSupportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/guides': typeof AdminGuidesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/popular-help': typeof AdminPopularHelpRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/guides/$slug': typeof PublicGuidesSlugRoute
  '/admin/guides/$id': typeof AdminGuidesIdRoute
  '/admin/guides/new': typeof AdminGuidesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/guides'
    | '/support'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/popular-help'
    | '/admin/site-content'
    | '/admin/versions'
    | '/admin/'
    | '/guides/$slug'
    | '/admin/guides/$id'
    | '/admin/guides/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/faq'
    | '/guides'
    | '/support'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/popular-help'
    | '/admin/site-content'
    | '/admin/versions'
    | '/'
    | '/admin'
    | '/guides/$slug'
    | '/admin/guides/$id'
    | '/admin/guides/new'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/faq'
    | '/_public/guides'
    | '/_public/support'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/popular-help'
    | '/admin/site-content'
    | '/admin/versions'
    | '/_public/'
    | '/admin/'
    | '/_public/guides/$slug'
    | '/admin/guides/$id'
    | '/admin/guides/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/versions': {
      id: '/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AdminVersionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popular-help': {
      id: '/admin/popular-help'
      path: '/popular-help'
      fullPath: '/admin/popular-help'
      preLoaderRoute: typeof AdminPopularHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/support': {
      id: '/_public/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PublicSupportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/guides': {
      id: '/_public/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof PublicGuidesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/guides/new': {
      id: '/admin/guides/new'
      path: '/new'
      fullPath: '/admin/guides/new'
      preLoaderRoute: typeof AdminGuidesNewRouteImport
      parentRoute: typeof AdminGuidesRoute
    }
    '/admin/guides/$id': {
      id: '/admin/guides/$id'
      path: '/$id'
      fullPath: '/admin/guides/$id'
      preLoaderRoute: typeof AdminGuidesIdRouteImport
      parentRoute: typeof AdminGuidesRoute
    }
    '/_public/guides/$slug': {
      id: '/_public/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof PublicGuidesSlugRouteImport
      parentRoute: typeof PublicGuidesRoute
    }
  }
}

interface PublicGuidesRouteChildren {
  PublicGuidesSlugRoute: typeof PublicGuidesSlugRoute
}

const PublicGuidesRouteChildren: PublicGuidesRouteChildren = {
  PublicGuidesSlugRoute: PublicGuidesSlugRoute,
}

const PublicGuidesRouteWithChildren = PublicGuidesRoute._addFileChildren(
  PublicGuidesRouteChildren,
)

interface PublicRouteChildren {
  PublicFaqRoute: typeof PublicFaqRoute
  PublicGuidesRoute: typeof PublicGuidesRouteWithChildren
  PublicSupportRoute: typeof PublicSupportRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFaqRoute: PublicFaqRoute,
  PublicGuidesRoute: PublicGuidesRouteWithChildren,
  PublicSupportRoute: PublicSupportRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminGuidesRouteChildren {
  AdminGuidesIdRoute: typeof AdminGuidesIdRoute
  AdminGuidesNewRoute: typeof AdminGuidesNewRoute
}

const AdminGuidesRouteChildren: AdminGuidesRouteChildren = {
  AdminGuidesIdRoute: AdminGuidesIdRoute,
  AdminGuidesNewRoute: AdminGuidesNewRoute,
}

const AdminGuidesRouteWithChildren = AdminGuidesRoute._addFileChildren(
  AdminGuidesRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminGuidesRoute: typeof AdminGuidesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPopularHelpRoute: typeof AdminPopularHelpRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminVersionsRoute: typeof AdminVersionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminGuidesRoute: AdminGuidesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPopularHelpRoute: AdminPopularHelpRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminVersionsRoute: AdminVersionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
