import {
  Activity, Archive, ArrowRightLeft, BarChart3, CheckCircle2, Clock3, FileText, Headphones,
  Image as ImageIcon, LayoutDashboard, LogOut, MessageCircle, MoreHorizontal, Paperclip, Plus,
  RefreshCw, Save, Search, Send, ShieldCheck, StickyNote, UserRound, Users, Wifi, WifiOff, Zap,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import {
  api, saveToken, saveSession, actorMode, getStaffPlatformRoute, token, websocketUrl, openStaffConversationStream, consumeStaffEventStream,
  type Conversation, type ConversationDetail, type Staff, type StaffSettings, type SupportMessage,
} from "./api";

type View = "dashboard" | "conversations" | "archive" | "performance" | "profile" | "staff";
type QueueTab = "waiting" | "mine" | "team" | "transferred" | "closed";
type RightTab = "conversation" | "shortcuts";
type SocketState = "connecting" | "connected" | "reconnecting" | "offline";
type QuickReply = { id:number; scope_kind:string; title:string; shortcut?:string; category:string; message_text:string };
type ComposerMode = "reply" | "note";

const queueTabs: Array<{ key: QueueTab; label: string }> = [
  { key: "waiting", label: "Waiting" }, { key: "mine", label: "Mine" }, { key: "team", label: "Team" },
  { key: "transferred", label: "Transferred" }, { key: "closed", label: "Resolved" },
];

function formatDate(value?: string, zone?: string) {
  if (!value) return "—";
  return new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",month:"short",day:"2-digit",...(zone?{timeZone:zone}:{})}).format(new Date(value));
}
function formatDuration(seconds: unknown) { const v=Math.max(0,Number(seconds||0)); if(v<60)return `${v}s`; const m=Math.floor(v/60); if(m<60)return `${m}m`; return `${Math.floor(m/60)}h ${m%60}m`; }
function mergeMessage(list:SupportMessage[],message:SupportMessage){return [...list.filter((x)=>x.id!==message.id&&(!message.client_message_id||x.client_message_id!==message.client_message_id)),message].sort((a,b)=>Number(a.message_sequence||0)-Number(b.message_sequence||0));}
function statusLabel(value:string){return String(value||"").replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,(x)=>x.toUpperCase());}

function Login({onLogin}:{onLogin:(staff:Staff,settings:StaffSettings)=>void}){
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[twofa,setTwofa]=useState(""),[mode,setMode]=useState<"STAFF"|"ADMIN">("STAFF"),[need2fa,setNeed2fa]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response:any=await api.login(email,password,mode,twofa);if(response?.twofa_required){setNeed2fa(true);setError("Enter your administrator 2FA code to continue.");return;}saveSession(response.access_token,mode);const me=await api.me();onLogin(me.staff,me.settings);}catch(c){setError(c instanceof Error?c.message:"Login failed");}finally{setBusy(false);}}
  return <main className="login-screen"><form className="login-card" onSubmit={submit}><div className="brand-block"><ShieldCheck/><div><strong>Luke CS Workspace</strong><span>Platform-scoped customer service access</span></div></div><div className="login-mode"><button type="button" className={mode==="STAFF"?"active":""} onClick={()=>{setMode("STAFF");setNeed2fa(false);}}>Staff</button><button type="button" className={mode==="ADMIN"?"active":""} onClick={()=>setMode("ADMIN")}>Administrator</button></div><label>Email<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" required value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password"/></label>{mode==="ADMIN"&&need2fa&&<label>2FA code<input inputMode="numeric" value={twofa} onChange={(e)=>setTwofa(e.target.value)} autoComplete="one-time-code"/></label>}{error&&<div className="error-banner">{error}</div>}<button className="primary-button" disabled={busy}>{busy?"Signing in…":mode==="ADMIN"?"Sign in as administrator":"Sign in as staff"}</button><p className="login-scope-note">Staff accounts can only access this Support Workspace. Administrator accounts can access both Admin Control and the Support Workspace.</p></form></main>;
}

export default function App(){
  const [staff,setStaff]=useState<Staff|null>(null),[settings,setSettings]=useState<StaffSettings>({platform_timezone:"UTC",heartbeat_interval_seconds:30});
  const [view,setView]=useState<View>("dashboard"),[tab,setTab]=useState<QueueTab>("waiting"),[rightTab,setRightTab]=useState<RightTab>("conversation");
  const [conversations,setConversations]=useState<Conversation[]>([]),[detail,setDetail]=useState<ConversationDetail|null>(null),[selectedId,setSelectedId]=useState<number|null>(null);
  const [performance,setPerformance]=useState<Record<string,any>>({}),[onlineStaff,setOnlineStaff]=useState<Staff[]>([]),[quickReplies,setQuickReplies]=useState<QuickReply[]>([]),[transferRequests,setTransferRequests]=useState<Array<Record<string,any>>>([]),[context,setContext]=useState<Record<string,any>|null>(null);
  const [draft,setDraft]=useState(""),[composerMode,setComposerMode]=useState<ComposerMode>("reply"),[search,setSearch]=useState(""),[quickSearch,setQuickSearch]=useState(""),[error,setError]=useState(""),[socketState,setSocketState]=useState<SocketState>("offline"),[uploading,setUploading]=useState(false),[streamStatus,setStreamStatus]=useState("syncing");
  const selectedRef=useRef<number|null>(null),sequenceRef=useRef(0),socketRef=useRef<WebSocket|null>(null),streamAbortRef=useRef<AbortController|null>(null),fileRef=useRef<HTMLInputElement|null>(null),messagePaneRef=useRef<HTMLDivElement|null>(null);
  const isAdmin=staff?.actor_type==="ADMIN"||actorMode()==="ADMIN";
  const zone=staff?.use_platform_timezone===false&&staff.timezone?staff.timezone:settings.platform_timezone||"UTC";
  const canReply=Boolean(detail&&staff&&detail.conversation.control_mode==="HUMAN"&&["WAITING_FOR_AGENT","ASSIGNED","AGENT_ACTIVE","TRANSFER_REQUESTED"].includes(detail.conversation.status)&&(isAdmin||Number(detail.conversation.assigned_staff_id||0)===staff.id));
  const canUpload=canReply&&settings.staff_attachments_enabled!==false;
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?conversations.filter((x)=>[x.customer_display_name,x.customer_identifier,x.last_message,x.assigned_staff_name,x.handoff_reason].some((v)=>String(v||"").toLowerCase().includes(q))):conversations;},[conversations,search]);
  const shownQuickReplies=useMemo(()=>{const q=quickSearch.toLowerCase().trim();return quickReplies.filter((x)=>!q||`${x.title} ${x.shortcut||""} ${x.category} ${x.message_text}`.toLowerCase().includes(q));},[quickReplies,quickSearch]);
  const scrollLatest=useCallback(()=>requestAnimationFrame(()=>{const el=messagePaneRef.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:"smooth"});}),[]);

  const loadConversation=useCallback(async(id:number)=>{try{const value=await api.conversation(id);setDetail({...value,messages:Array.isArray(value.messages)?value.messages:[]});setSelectedId(id);selectedRef.current=id;sequenceRef.current=Math.max(0,...(value.messages||[]).map((m)=>Number(m.message_sequence||0)));setContext((await api.customerContext(id).catch(()=>({context:null}))).context||null);requestAnimationFrame(()=>{const el=messagePaneRef.current;if(el)el.scrollTop=el.scrollHeight;});}catch(c){setError(c instanceof Error?c.message:"Could not load conversation");}},[]);
  const loadList=useCallback(async()=>{if(!staff)return;try{setConversations(await api.conversations(view==="archive"?"closed":tab));}catch(c){setError(c instanceof Error?c.message:"Could not load conversations");}},[staff,tab,view]);
  const loadShared=useCallback(async()=>{if(!staff)return;const [perf,online,replies,transfers]=await Promise.all([api.performance("day").catch(()=>({})),api.online().catch(()=>[]),api.quickReplies().catch(()=>[]),api.transfers("requested").catch(()=>[])]);setPerformance(perf);setOnlineStaff(online);setQuickReplies(replies);setTransferRequests(transfers);},[staff]);
  const refresh=useCallback(async()=>{setError("");await Promise.all([loadList(),loadShared()]);if(selectedRef.current)await loadConversation(selectedRef.current);},[loadList,loadShared,loadConversation]);
  const syncCurrent=useCallback(async()=>{const id=selectedRef.current;if(!id)return;try{const data=await api.sync(id,sequenceRef.current);setDetail((current)=>current?{...current,conversation:data.conversation||current.conversation,messages:(data.messages||[]).reduce((list,message)=>mergeMessage(list,message),current.messages)}:current);for(const message of data.messages||[])sequenceRef.current=Math.max(sequenceRef.current,Number(message.message_sequence||0));if((data.messages||[]).length)scrollLatest();}catch{}},[]);

  useEffect(()=>{if(token())api.me().then((x)=>{setStaff(x.staff);setSettings(x.settings);}).catch(()=>saveToken(""));},[]);
  useEffect(()=>{if(!staff)return;void refresh();const timer=window.setInterval(()=>{void loadList();if(selectedRef.current)void syncCurrent();},socketState==="connected"?12000:2500);return()=>clearInterval(timer);},[staff?.id,tab,view,socketState,refresh,loadList,syncCurrent]);
  useEffect(()=>{if(!staff)return;const timer=window.setInterval(()=>api.heartbeat(staff.availability_status).catch(()=>undefined),Math.max(15,Number(settings.heartbeat_interval_seconds||30))*1000);return()=>clearInterval(timer);},[staff?.id,staff?.availability_status,settings.heartbeat_interval_seconds]);
  useEffect(()=>{if(!staff||!token()||isAdmin){setSocketState(isAdmin?"connected":"offline");return;}let disposed=false;let reconnect:number|undefined;const connect=async()=>{setSocketState(socketRef.current?"reconnecting":"connecting");try{const ticket=await api.realtimeTicket();if(disposed)return;const ws=new WebSocket(websocketUrl(ticket.ticket));socketRef.current=ws;ws.onopen=()=>{setSocketState("connected");if(selectedRef.current)ws.send(JSON.stringify({event:"support:subscribe",data:{conversation_id:selectedRef.current}}));};ws.onmessage=(ev)=>{try{const packet=JSON.parse(ev.data);const message=packet?.data?.message;if(message&&selectedRef.current===Number(message.conversation_id||packet.conversation_id)){setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,message)}:d);sequenceRef.current=Math.max(sequenceRef.current,Number(message.message_sequence||0));}if(["support:queue_updated","support:conversation_assigned","support:conversation_resolved"].includes(packet.event))void loadList();}catch{}};ws.onclose=()=>{setSocketState("offline");if(!disposed)reconnect=window.setTimeout(connect,2000);};ws.onerror=()=>ws.close();}catch{setSocketState("offline");if(!disposed)reconnect=window.setTimeout(connect,3000);}};void connect();return()=>{disposed=true;if(reconnect)clearTimeout(reconnect);socketRef.current?.close();};},[staff?.id,loadList]);
  useEffect(()=>{streamAbortRef.current?.abort();if(!staff||!selectedId)return;const controller=new AbortController();streamAbortRef.current=controller;let retry:number|undefined;const connect=async()=>{setStreamStatus("syncing");try{const response=await openStaffConversationStream(selectedId,sequenceRef.current,controller.signal);setStreamStatus("live");await consumeStaffEventStream(response,(packet)=>{const message=packet.data?.message;if(message){setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,message)}:d);sequenceRef.current=Math.max(sequenceRef.current,Number(message.message_sequence||0));scrollLatest();}if(packet.event==="conversation.resolved"||packet.event==="conversation.assigned")void loadConversation(selectedId);},controller.signal);}catch{if(!controller.signal.aborted){setStreamStatus("fallback");retry=window.setTimeout(connect,2500);}}};void connect();return()=>{controller.abort();if(retry)clearTimeout(retry);};},[staff?.id,selectedId,loadConversation]);

  async function changePresence(status:"active"|"invisible"){if(!staff)return;await api.presence(status);setStaff({...staff,availability_status:status});}
  async function accept(item:Conversation){try{if(!isAdmin)await api.accept(item.id);setView("conversations");setTab(isAdmin?"team":"mine");await loadConversation(item.id);await loadList();}catch(c){setError(c instanceof Error?c.message:"Could not open conversation");}}
  async function send(){if(!detail||!draft.trim()||!canReply)return;const text=draft;setDraft("");try{if(composerMode==="note"){await api.note(detail.conversation.id,text);await loadConversation(detail.conversation.id);}else{const result=await api.reply(detail.conversation.id,text);setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,result.message)}:d);scrollLatest();}}catch(c){setDraft(text);setError(c instanceof Error?c.message:"Message failed");}}
  function addNote(){setComposerMode("note");requestAnimationFrame(()=>document.querySelector<HTMLTextAreaElement>(".composer textarea")?.focus());}
  async function transfer(){if(!detail)return;const active=onlineStaff.filter((x)=>x.id!==staff?.id&&x.availability_status==="active");if(!active.length){setError("No other Active staff member is available.");return;}const name=prompt(`Transfer to: ${active.map((x)=>`${x.id}=${x.display_name}`).join(", ")}`);const target=active.find((x)=>String(x.id)===String(name)||x.display_name.toLowerCase()===String(name||"").toLowerCase());if(!target)return;const reason=prompt("Transfer reason:")||"Customer needs another representative";await api.transfer(detail.conversation.id,target.id,reason);await loadConversation(detail.conversation.id);}
  async function transferDecision(id:number,action:"accept"|"reject"){try{await api.transferDecision(id,action);await refresh();if(action==="accept"){const request=transferRequests.find((x)=>Number(x.id)===id);if(request?.conversation_id){setView("conversations");setTab("mine");await loadConversation(Number(request.conversation_id));}}}catch(c){setError(c instanceof Error?c.message:"Transfer decision failed");}}
  async function resolve(){if(!detail)return;if(!confirm("Resolve and return the customer to platform support?"))return;await api.resolve(detail.conversation.id);await loadConversation(detail.conversation.id);await loadList();}
  async function upload(file:File){if(!detail||!canUpload)return;setUploading(true);try{const result=await api.uploadAttachment(detail.conversation.id,file);setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,result.message)}:d);}catch(c){setError(c instanceof Error?c.message:"Upload failed");}finally{setUploading(false);if(fileRef.current)fileRef.current.value="";}}
  function insertQuickReply(reply:QuickReply){if(!canReply)return;setDraft((current)=>current?`${current}\n${reply.message_text}`:reply.message_text);}
  async function createPersonalReply(){const title=prompt("Quick reply title:");if(!title)return;const message=prompt("Quick reply message:");if(!message)return;await api.createQuickReply({title,message_text:message,category:"Personal"});setQuickReplies(await api.quickReplies());}
  async function logout(){try{await api.logout();}catch{}saveSession("",isAdmin?"ADMIN":"STAFF");setStaff(null);}

  if(!staff){const sharedHost=(()=>{try{return new URL(String(import.meta.env.VITE_LUKE_SHARED_STAFF_ORIGIN||"https://cs.ar-ai666.com")).hostname.toLowerCase();}catch{return "cs.ar-ai666.com";}})();if(typeof window!=="undefined"&&window.location.hostname.toLowerCase()===sharedHost&&!getStaffPlatformRoute())return <main className="login-screen"><section className="login-card incomplete-link"><ShieldCheck/><h2>This workspace link is incomplete.</h2><p>Use the platform-specific CS Workspace link supplied by your administrator.</p><code>https://{sharedHost}/p/&lt;platform-route&gt;</code></section></main>;return <Login onLogin={(s,st)=>{setStaff(s);setSettings(st);}}/>;}
  return <div className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><Headphones/><div><strong>Luke CS Workspace</strong><small>{staff.public_display_name||staff.display_name}{isAdmin?" · Administrator":""}</small></div></div><nav>
      <button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}><LayoutDashboard/>Dashboard</button>
      <button className={view==="conversations"?"active":""} onClick={()=>setView("conversations")}><MessageCircle/>Conversations</button>
      <button className={view==="archive"?"active":""} onClick={()=>{setView("archive");setTab("closed");}}><Archive/>Archive</button>
      <button className={view==="performance"?"active":""} onClick={()=>setView("performance")}><BarChart3/>Performance</button>{!isAdmin&&<button className={view==="profile"?"active":""} onClick={()=>setView("profile")}><UserRound/>My Profile</button>}{isAdmin&&<button className={view==="staff"?"active":""} onClick={()=>setView("staff")}><Users/>Staff Management</button>}
    </nav><div className="sidebar-footer"><div className={`connection ${socketState}`}><span/>{socketState==="connected"?"Realtime connected":socketState==="offline"?"Fallback syncing":"Reconnecting"}</div><button onClick={logout}><LogOut/>Logout</button></div></aside>
    <section className="workspace-shell"><header className="topbar"><div><h1>{view==="dashboard"?"Dashboard":view==="performance"?"Performance":view==="profile"?"My Profile":view==="staff"?"Staff Management":"Customer Conversations"}</h1><p>{staff.email}</p></div><div className="top-actions">{isAdmin?<span className="admin-mode-badge">Administrator</span>:<div className="availability"><button className={staff.availability_status==="active"?"active":""} onClick={()=>changePresence("active")}>Active</button><button className={staff.availability_status==="invisible"?"active":""} onClick={()=>changePresence("invisible")}>Invisible</button></div>}<button className="icon-button" onClick={refresh}><RefreshCw/></button></div></header>{error&&<div className="global-error">{error}<button onClick={()=>setError("")}>×</button></div>}
      {view==="dashboard"&&<Dashboard conversations={conversations} performance={performance} transferRequests={transferRequests} onOpen={(id)=>{setView("conversations");void loadConversation(id);}} onAccept={accept} onTransferDecision={transferDecision} zone={zone}/>} 
      {(view==="conversations"||view==="archive")&&<div className="professional-workspace">
        <aside className="conversation-rail"><div className="queue-tabs">{queueTabs.filter((x)=>(view!=="archive"||x.key==="closed")&&(!isAdmin||!["mine","transferred"].includes(x.key))).map((x)=><button className={tab===x.key?"active":""} key={x.key} onClick={()=>{setTab(x.key);setDetail(null);setSelectedId(null);}}>{x.label}</button>)}</div><div className="search-box"><Search/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search conversations"/></div><div className="conversation-list">{filtered.map((item)=><article key={item.id} className={selectedId===item.id?"selected":""} onClick={()=>loadConversation(item.id)}><div className="list-head"><span className="avatar"><UserRound/></span><div><strong>{item.customer_display_name||item.customer_identifier||`Customer ${item.id}`}</strong><small>#{item.id} · {formatDate(item.last_message_at||item.queue_entered_at,zone)}</small></div>{Number(item.unread_count||0)>0&&<b>{item.unread_count}</b>}</div><p>{item.last_message||statusLabel(item.handoff_reason||item.status)}</p><footer><span className={`status-dot ${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span>{tab==="waiting"&&<button onClick={(e)=>{e.stopPropagation();void accept(item);}}>Accept</button>}</footer></article>)}{!filtered.length&&<div className="empty-list">No conversations.</div>}</div></aside>
        <main className="conversation-main">{detail?<><header className="conversation-header"><div><h2>{detail.conversation.customer_display_name||detail.conversation.customer_identifier||`Customer ${detail.conversation.id}`}</h2><p><span className={`status-dot ${detail.conversation.status.toLowerCase()}`}>{statusLabel(detail.conversation.status)}</span> · {detail.conversation.assigned_staff_name||"Unassigned"} · {streamStatus==="live"?"Live":streamStatus==="fallback"?"Fallback sync":"Syncing"}</p></div><div className="conversation-actions"><button onClick={addNote}><StickyNote/>Note</button>{canReply&&<button onClick={transfer}><ArrowRightLeft/>Transfer</button>}{canReply&&<button className="resolve" onClick={resolve}><CheckCircle2/>Resolve</button>}<button><MoreHorizontal/></button></div></header><div className="message-pane" ref={messagePaneRef}><Timeline detail={detail} zone={zone} settings={settings}/></div><footer className={`composer ${composerMode==="note"?"note-mode":""}`}><div className="composer-toolbar"><button className={composerMode==="reply"?"active":""} onClick={()=>setComposerMode("reply")}>Reply</button><button className={composerMode==="note"?"active note-active":""} onClick={addNote}><StickyNote/>Internal Note</button><span/>{canUpload&&composerMode==="reply"&&<><button title="Upload image or file" onClick={()=>fileRef.current?.click()}><Paperclip/></button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp,application/pdf,text/plain" onChange={(e)=>e.target.files?.[0]&&void upload(e.target.files[0])}/></>}<button onClick={()=>setRightTab("shortcuts")}><Zap/></button></div>{composerMode==="note"&&<div className="internal-note-warning">🔒 Internal Note · visible only to staff and administrators</div>}<div className="composer-input"><textarea disabled={!canReply||uploading} value={draft} onChange={(e)=>setDraft(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder={canReply?(composerMode==="note"?"Write an internal note…":"Type a reply…"):`Read-only — assigned to ${detail.conversation.assigned_staff_name||"another representative"}`}/><button disabled={!canReply||!draft.trim()||uploading} onClick={send}>{composerMode==="note"?<StickyNote/>:<Send/>}</button></div></footer></>:<div className="empty-conversation"><MessageCircle/><h2>Select a conversation</h2><p>Waiting conversations can be accepted directly by Active staff.</p></div>}</main>
        <aside className="context-panel"><div className="right-tabs"><button className={rightTab==="conversation"?"active":""} onClick={()=>setRightTab("conversation")}>Conversation</button><button className={rightTab==="shortcuts"?"active":""} onClick={()=>setRightTab("shortcuts")}>Shortcuts</button></div>{rightTab==="conversation"?<ConversationContext detail={detail} context={context} zone={zone}/>:<Shortcuts replies={shownQuickReplies} search={quickSearch} onSearch={setQuickSearch} onUse={insertQuickReply} onCreate={createPersonalReply}/>}</aside>
      </div>}
      {view==="performance"&&<Performance data={performance}/>} {!isAdmin&&view==="profile"&&<StaffProfile staff={staff} settings={settings} onUpdated={setStaff} onError={setError}/>} {view==="staff"&&isAdmin&&<StaffManagement staff={onlineStaff} onForceLogout={async(id)=>{await api.forceLogoutStaff(id);await loadShared();}}/>} 
    </section>
  </div>;
}

function Timeline({detail,zone,settings}:{detail:ConversationDetail;zone:string;settings:StaffSettings}){
  const items=[...detail.messages.filter((m)=>!m.is_internal).map((message)=>({kind:"message" as const,at:message.created_at||"",id:`m-${message.id}`,message})),...detail.notes.map((note)=>({kind:"note" as const,at:note.created_at||"",id:`n-${note.id}`,note}))].sort((a,b)=>new Date(a.at||0).getTime()-new Date(b.at||0).getTime());
  return <>{items.map((item)=>item.kind==="note"?<div className="internal-note-card" key={item.id}><div>🔒 <strong>Internal Note</strong></div><p>{item.note.note_text}</p><small>{item.note.author_name||"Support"} · {formatDate(item.note.created_at,zone)}</small></div>:<MessageBubble key={item.id} message={item.message} zone={zone} settings={settings}/>)}</>;
}
function MessageBubble({message,zone,settings}:{message:SupportMessage;zone:string;settings:StaffSettings}){
  if(message.sender_type==="SYSTEM")return <div className="system-message"><Activity/><span>{message.body_text}</span><time>{formatDate(message.created_at,zone)}</time></div>;
  const image=message.message_type==="image"&&message.attachment_url; const file=message.message_type==="attachment"&&message.attachment_url;
  const outbound=message.sender_type!=="CUSTOMER"; const avatar=message.sender_avatar_url||(message.sender_type==="AI"?settings.automated_support_avatar_url:""); const name=message.sender_type==="AI"?(settings.automated_support_display_name||message.sender_name||"Support"):(message.sender_name||message.sender_type);
  return <div className={`message-row ${outbound?"outbound":"inbound"}`}>{outbound&&<span className="chat-head">{avatar?<img src={avatar} alt=""/>:<Headphones/>}</span>}<div className={`message ${message.sender_type.toLowerCase()}`}><div className="message-author"><strong>{name}</strong><time>{formatDate(message.created_at,zone)}</time></div>{image&&<a href={message.attachment_url} target="_blank" rel="noreferrer"><img src={message.attachment_url} alt={message.attachment_name||"Shared image"}/></a>}{file&&<a className="file-card" href={message.attachment_url} target="_blank" rel="noreferrer"><FileText/><span><strong>{message.attachment_name||"Attachment"}</strong><small>{message.attachment_content_type||"File"}</small></span></a>}{message.body_text&&<p>{message.body_text}</p>}{message.sender_type==="STAFF"&&<small className="delivery">{message.read_at?"Read":message.delivered_at?"Delivered":"Sent"}</small>}</div>{!outbound&&<span className="chat-head customer-head"><UserRound/></span>}</div>;
}
function ConversationContext({detail,context,zone}:{detail:ConversationDetail|null;context:Record<string,any>|null;zone:string}){if(!detail)return <div className="right-empty"><UserRound/><p>Select a conversation to view customer information.</p></div>;return <div className="context-sections"><section><h3>Visitor Information</h3><dl><dt>Customer</dt><dd>{detail.conversation.customer_display_name||detail.conversation.customer_identifier||"Not set"}</dd><dt>Language</dt><dd>{detail.conversation.customer_locale||"Not set"}</dd><dt>IP address</dt><dd>{context?.ip_address||"Not available"}</dd><dt>Region</dt><dd>{[context?.region_name,context?.country_code].filter(Boolean).join(", ")||"Not available"}</dd></dl></section><section><h3>Device Information</h3><dl><dt>Device</dt><dd>{context?.device_type||"Not available"}</dd><dt>Operating system</dt><dd>{context?.operating_system||"Not available"}</dd><dt>Browser</dt><dd>{[context?.browser_name,context?.browser_version].filter(Boolean).join(" ")||"Not available"}</dd><dt>Current page</dt><dd className="break">{context?.current_url||"Not available"}</dd></dl></section><section><h3>Conversation</h3><dl><dt>Started</dt><dd>{formatDate(detail.conversation.created_at||detail.conversation.queue_entered_at,zone)}</dd><dt>Handoff reason</dt><dd>{statusLabel(detail.conversation.handoff_reason||"Not specified")}</dd><dt>Assigned</dt><dd>{detail.conversation.assigned_staff_name||"Unassigned"}</dd><dt>Control</dt><dd>{detail.conversation.control_mode}</dd></dl></section><section><h3>Internal Notes</h3>{detail.notes.map((n)=><article className="note" key={n.id}><p>{n.note_text}</p><small>{n.author_name||"Staff"} · {formatDate(n.created_at,zone)}</small></article>)}{!detail.notes.length&&<p className="muted">No internal notes.</p>}</section></div>}
function Shortcuts({replies,search,onSearch,onUse,onCreate}:{replies:QuickReply[];search:string;onSearch:(v:string)=>void;onUse:(r:QuickReply)=>void;onCreate:()=>void}){return <div className="shortcuts"><div className="search-box"><Search/><input value={search} onChange={(e)=>onSearch(e.target.value)} placeholder="Search quick replies"/></div><button className="create-shortcut" onClick={onCreate}><Plus/>New personal reply</button>{replies.map((r)=><article key={r.id} onClick={()=>onUse(r)}><header><strong>{r.title}</strong><span>{r.scope_kind}</span></header><small>{r.category}{r.shortcut?` · ${r.shortcut}`:""}</small><p>{r.message_text}</p></article>)}{!replies.length&&<p className="muted">No quick replies available.</p>}</div>}
function StaffProfile({staff,settings,onUpdated,onError}:{staff:Staff;settings:StaffSettings;onUpdated:(staff:Staff)=>void;onError:(message:string)=>void}){
  const [displayName,setDisplayName]=useState(staff.display_name||"");
  const [profileAvatar,setProfileAvatar]=useState(staff.profile_avatar_url||"");
  const [publicName,setPublicName]=useState(staff.public_display_name||staff.display_name||"");
  const [publicAvatar,setPublicAvatar]=useState(staff.public_avatar_url||"");
  const [saving,setSaving]=useState(false),[uploadingProfile,setUploadingProfile]=useState(false),[uploadingPublic,setUploadingPublic]=useState(false);
  const internalRef=useRef<HTMLInputElement|null>(null),publicRef=useRef<HTMLInputElement|null>(null);
  useEffect(()=>{setDisplayName(staff.display_name||"");setProfileAvatar(staff.profile_avatar_url||"");setPublicName(staff.public_display_name||staff.display_name||"");setPublicAvatar(staff.public_avatar_url||"");},[staff.id,staff.display_name,staff.profile_avatar_url,staff.public_display_name,staff.public_avatar_url]);
  const enabled=settings.staff_profile_edit_enabled!==false,publicEnabled=enabled&&settings.staff_public_identity_edit_enabled!==false;
  async function uploadImage(file:File,target:"profile"|"public"){target==="profile"?setUploadingProfile(true):setUploadingPublic(true);try{const result=await api.uploadProfileImage(file);if(target==="profile")setProfileAvatar(result.url);else setPublicAvatar(result.url);}catch(error){onError(error instanceof Error?error.message:"Image upload failed");}finally{target==="profile"?setUploadingProfile(false):setUploadingPublic(false);}}
  async function save(){if(!enabled)return;setSaving(true);try{const result=await api.updateProfile({display_name:displayName,profile_avatar_url:profileAvatar,public_display_name:publicName,public_avatar_url:publicAvatar});onUpdated(result.staff);}catch(error){onError(error instanceof Error?error.message:"Profile update failed");}finally{setSaving(false);}}
  return <div className="profile-page"><section className="profile-card"><header><div><h2>My Profile</h2><p>Manage your CS account and the identity customers see during human support.</p></div><button className="primary-button profile-save" disabled={!enabled||saving} onClick={()=>void save()}><Save/>{saving?"Saving…":"Save changes"}</button></header>{!enabled&&<div className="profile-policy-note">Your administrator has disabled staff profile editing for this platform.</div>}<div className="profile-grid"><div className="profile-section"><h3>Account Profile</h3><p className="muted">Used inside the CS Workspace.</p><AvatarEditor url={profileAvatar} fallback={displayName} label="Profile picture" busy={uploadingProfile} disabled={!enabled} onChoose={()=>internalRef.current?.click()} onClear={()=>setProfileAvatar("")}/><input ref={internalRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>e.target.files?.[0]&&void uploadImage(e.target.files[0],"profile")}/><label>Display name<input disabled={!enabled} value={displayName} onChange={(e)=>setDisplayName(e.target.value)} maxLength={160}/></label></div><div className="profile-section"><h3>Customer-facing Identity</h3><p className="muted">Shown as your name and chat head when you reply to customers.</p><AvatarEditor url={publicAvatar} fallback={publicName} label="Chat avatar" busy={uploadingPublic} disabled={!publicEnabled} onChoose={()=>publicRef.current?.click()} onClear={()=>setPublicAvatar("")}/><input ref={publicRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>e.target.files?.[0]&&void uploadImage(e.target.files[0],"public")}/><label>Public support name<input disabled={!publicEnabled} value={publicName} onChange={(e)=>setPublicName(e.target.value)} maxLength={160}/></label><button className="secondary-button" disabled={!publicEnabled||!profileAvatar} onClick={()=>setPublicAvatar(profileAvatar)}>Use profile picture as chat avatar</button>{!publicEnabled&&<div className="profile-policy-note compact">Customer-facing identity is managed by your administrator.</div>}</div></div><div className="identity-preview"><span className="chat-head">{publicAvatar?<img src={publicAvatar} alt=""/>:<Headphones/>}</span><div><strong>{publicName||"Support"}</strong><p>This is how your support identity will appear to customers.</p></div></div></section></div>;
}
function AvatarEditor({url,fallback,label,busy,disabled,onChoose,onClear}:{url:string;fallback:string;label:string;busy:boolean;disabled:boolean;onChoose:()=>void;onClear:()=>void}){return <div className="avatar-editor"><div className="profile-avatar">{url?<img src={url} alt=""/>:<span>{String(fallback||"S").slice(0,1).toUpperCase()}</span>}</div><div><strong>{label}</strong><div className="avatar-actions"><button type="button" disabled={disabled||busy} onClick={onChoose}>{busy?"Uploading…":"Upload image"}</button>{url&&<button type="button" disabled={disabled||busy} onClick={onClear}>Remove</button>}</div><small>PNG, JPEG or WebP · maximum 5 MB</small></div></div>}
function StaffManagement({staff,onForceLogout}:{staff:Staff[];onForceLogout:(id:number)=>Promise<void>}){return <div className="dashboard"><section className="dashboard-table"><header><div><h2>Staff Management</h2><p>Administrator operational controls for this platform only.</p></div></header>{staff.map((member)=><article key={member.id}><div><strong>{member.public_display_name||member.display_name}</strong><p>{member.email}</p><small>{statusLabel(member.availability_status)} · {member.role_key||"support agent"}</small></div><button onClick={()=>void onForceLogout(member.id)}>Force logout</button></article>)}{!staff.length&&<div className="empty-list">No staff accounts are available.</div>}</section></div>}
function Dashboard({conversations,performance,transferRequests,onOpen,onAccept,onTransferDecision,zone}:{conversations:Conversation[];performance:Record<string,any>;transferRequests:Array<Record<string,any>>;onOpen:(id:number)=>void;onAccept:(c:Conversation)=>void;onTransferDecision:(id:number,action:"accept"|"reject")=>void;zone:string}){const waiting=conversations.filter((x)=>x.status==="WAITING_FOR_AGENT");return <div className="dashboard"><div className="metric-grid"><Metric icon={Users} label="Waiting" value={waiting.length}/><Metric icon={MessageCircle} label="Served today" value={Number(performance.conversations_served||0)}/><Metric icon={CheckCircle2} label="Resolved" value={Number(performance.resolved_conversations||0)}/><Metric icon={Clock3} label="First response" value={formatDuration(performance.avg_first_response_seconds)}/></div>{transferRequests.length>0&&<section className="dashboard-table transfer-requests"><header><div><h2>Transfer Requests</h2><p>Ownership changes only after you accept.</p></div></header>{transferRequests.map((request)=><article key={request.id}><div><strong>{request.customer_display_name||request.customer_identifier||`Conversation ${request.conversation_id}`}</strong><p>{request.reason||"Transfer requested"}</p><small>From {request.from_staff_name||"another representative"}</small></div><div className="transfer-actions"><button onClick={()=>onTransferDecision(Number(request.id),"reject")}>Reject</button><button className="primary-button" onClick={()=>onTransferDecision(Number(request.id),"accept")}>Accept</button></div></article>)}</section>}<section className="dashboard-table"><header><div><h2>Waiting Queue</h2><p>Active staff can accept conversations directly.</p></div></header>{waiting.slice(0,8).map((c)=><article key={c.id}><div><strong>{c.customer_display_name||c.customer_identifier||`Customer ${c.id}`}</strong><p>{c.last_message||statusLabel(c.handoff_reason||"New request")}</p><small>{formatDate(c.queue_entered_at,zone)}</small></div><button onClick={()=>onAccept(c)}>Accept</button></article>)}{!waiting.length&&<div className="empty-list">No customers are waiting.</div>}</section></div>}
function Performance({data}:{data:Record<string,any>}){return <div className="performance"><div className="metric-grid"><Metric icon={Users} label="Conversations" value={Number(data.conversations_served||0)}/><Metric icon={CheckCircle2} label="Resolved" value={Number(data.resolved_conversations||0)}/><Metric icon={Send} label="Replies" value={Number(data.replies_sent||0)}/><Metric icon={Clock3} label="Handling" value={formatDuration(data.avg_conversation_seconds)}/></div><section><h2>Professional service metrics</h2><p>Replies and resolved conversations are primary metrics. Sentence count is informational only.</p></section></div>}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}){return <article className="metric"><Icon/><div><span>{label}</span><strong>{value}</strong></div></article>}
