import {
  Activity, Archive, ArrowRightLeft, BarChart3, CheckCircle2, Clock3, FileText, Headphones,
  Image as ImageIcon, LayoutDashboard, LogOut, MessageCircle, MoreHorizontal, Paperclip, Plus,
  RefreshCw, Search, Send, ShieldCheck, StickyNote, UserRound, Users, Wifi, WifiOff, Zap,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import {
  api, saveToken, token, websocketUrl, openStaffConversationStream, consumeStaffEventStream,
  type Conversation, type ConversationDetail, type Staff, type StaffSettings, type SupportMessage,
} from "./api";

type View = "dashboard" | "conversations" | "archive" | "performance";
type QueueTab = "waiting" | "mine" | "team" | "transferred" | "closed";
type RightTab = "conversation" | "shortcuts";
type SocketState = "connecting" | "connected" | "reconnecting" | "offline";
type QuickReply = { id:number; scope_kind:string; title:string; shortcut?:string; category:string; message_text:string };

const queueTabs: Array<{ key: QueueTab; label: string }> = [
  { key: "waiting", label: "Waiting" }, { key: "mine", label: "Mine" }, { key: "team", label: "Team" },
  { key: "transferred", label: "Transferred" }, { key: "closed", label: "Resolved" },
];

function formatDate(value?: string, zone?: string) {
  if (!value) return "—";
  return new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",month:"short",day:"2-digit",...(zone?{timeZone:zone}:{})}).format(new Date(value));
}
function formatDuration(seconds: unknown) { const v=Math.max(0,Number(seconds||0)); if(v<60)return `${v}s`; const m=Math.floor(v/60); if(m<60)return `${m}m`; return `${Math.floor(m/60)}h ${m%60}m`; }
function mergeMessage(list:SupportMessage[],message:SupportMessage){return [...list.filter((x)=>x.id!==message.id&&(!message.client_message_id||x.client_message_id!==message.client_message_id)),message].sort((a,b)=>Number(a.message_sequence||0)-Number(b.message_sequence||0));}
function statusLabel(value:string){return String(value||"").replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,(x)=>x.toUpperCase());}

function Login({onLogin}:{onLogin:(staff:Staff,settings:StaffSettings)=>void}){
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await api.login(email,password);saveToken(response.access_token);const me=await api.me();onLogin(me.staff,me.settings);}catch(c){setError(c instanceof Error?c.message:"Login failed");}finally{setBusy(false);}}
  return <main className="login-screen"><form className="login-card" onSubmit={submit}><div className="brand-block"><ShieldCheck/><div><strong>Customer Service Console</strong><span>Secure platform-scoped staff access</span></div></div><label>Email<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" required value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<div className="error-banner">{error}</div>}<button className="primary-button" disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></main>;
}

export default function App(){
  const [staff,setStaff]=useState<Staff|null>(null),[settings,setSettings]=useState<StaffSettings>({platform_timezone:"UTC",heartbeat_interval_seconds:30});
  const [view,setView]=useState<View>("dashboard"),[tab,setTab]=useState<QueueTab>("waiting"),[rightTab,setRightTab]=useState<RightTab>("conversation");
  const [conversations,setConversations]=useState<Conversation[]>([]),[detail,setDetail]=useState<ConversationDetail|null>(null),[selectedId,setSelectedId]=useState<number|null>(null);
  const [performance,setPerformance]=useState<Record<string,any>>({}),[onlineStaff,setOnlineStaff]=useState<Staff[]>([]),[quickReplies,setQuickReplies]=useState<QuickReply[]>([]),[transferRequests,setTransferRequests]=useState<Array<Record<string,any>>>([]),[context,setContext]=useState<Record<string,any>|null>(null);
  const [draft,setDraft]=useState(""),[search,setSearch]=useState(""),[quickSearch,setQuickSearch]=useState(""),[error,setError]=useState(""),[socketState,setSocketState]=useState<SocketState>("offline"),[uploading,setUploading]=useState(false),[streamStatus,setStreamStatus]=useState("syncing");
  const selectedRef=useRef<number|null>(null),sequenceRef=useRef(0),socketRef=useRef<WebSocket|null>(null),streamAbortRef=useRef<AbortController|null>(null),fileRef=useRef<HTMLInputElement|null>(null),messagePaneRef=useRef<HTMLDivElement|null>(null);
  const zone=staff?.use_platform_timezone===false&&staff.timezone?staff.timezone:settings.platform_timezone||"UTC";
  const canReply=Boolean(detail&&staff&&Number(detail.conversation.assigned_staff_id||0)===staff.id&&detail.conversation.control_mode==="HUMAN"&&["ASSIGNED","AGENT_ACTIVE","TRANSFER_REQUESTED"].includes(detail.conversation.status));
  const canUpload=canReply&&settings.staff_attachments_enabled!==false;
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?conversations.filter((x)=>[x.customer_display_name,x.customer_identifier,x.last_message,x.assigned_staff_name,x.handoff_reason].some((v)=>String(v||"").toLowerCase().includes(q))):conversations;},[conversations,search]);
  const shownQuickReplies=useMemo(()=>{const q=quickSearch.toLowerCase().trim();return quickReplies.filter((x)=>!q||`${x.title} ${x.shortcut||""} ${x.category} ${x.message_text}`.toLowerCase().includes(q));},[quickReplies,quickSearch]);

  const loadConversation=useCallback(async(id:number)=>{try{const value=await api.conversation(id);setDetail({...value,messages:Array.isArray(value.messages)?value.messages:[]});setSelectedId(id);selectedRef.current=id;sequenceRef.current=Math.max(0,...(value.messages||[]).map((m)=>Number(m.message_sequence||0)));setContext((await api.customerContext(id).catch(()=>({context:null}))).context||null);requestAnimationFrame(()=>{const el=messagePaneRef.current;if(el)el.scrollTop=el.scrollHeight;});}catch(c){setError(c instanceof Error?c.message:"Could not load conversation");}},[]);
  const loadList=useCallback(async()=>{if(!staff)return;try{setConversations(await api.conversations(view==="archive"?"closed":tab));}catch(c){setError(c instanceof Error?c.message:"Could not load conversations");}},[staff,tab,view]);
  const loadShared=useCallback(async()=>{if(!staff)return;const [perf,online,replies,transfers]=await Promise.all([api.performance("day").catch(()=>({})),api.online().catch(()=>[]),api.quickReplies().catch(()=>[]),api.transfers("requested").catch(()=>[])]);setPerformance(perf);setOnlineStaff(online);setQuickReplies(replies);setTransferRequests(transfers);},[staff]);
  const refresh=useCallback(async()=>{setError("");await Promise.all([loadList(),loadShared()]);if(selectedRef.current)await loadConversation(selectedRef.current);},[loadList,loadShared,loadConversation]);
  const syncCurrent=useCallback(async()=>{const id=selectedRef.current;if(!id)return;try{const data=await api.sync(id,sequenceRef.current);setDetail((current)=>current?{...current,conversation:data.conversation||current.conversation,messages:(data.messages||[]).reduce((list,message)=>mergeMessage(list,message),current.messages)}:current);for(const message of data.messages||[])sequenceRef.current=Math.max(sequenceRef.current,Number(message.message_sequence||0));}catch{}},[]);

  useEffect(()=>{if(token())api.me().then((x)=>{setStaff(x.staff);setSettings(x.settings);}).catch(()=>saveToken(""));},[]);
  useEffect(()=>{if(!staff)return;void refresh();const timer=window.setInterval(()=>{void loadList();if(selectedRef.current)void syncCurrent();},socketState==="connected"?12000:2500);return()=>clearInterval(timer);},[staff?.id,tab,view,socketState,refresh,loadList,syncCurrent]);
  useEffect(()=>{if(!staff)return;const timer=window.setInterval(()=>api.heartbeat(staff.availability_status).catch(()=>undefined),Math.max(15,Number(settings.heartbeat_interval_seconds||30))*1000);return()=>clearInterval(timer);},[staff?.id,staff?.availability_status,settings.heartbeat_interval_seconds]);
  useEffect(()=>{if(!staff||!token())return;let disposed=false;let reconnect:number|undefined;const connect=async()=>{setSocketState(socketRef.current?"reconnecting":"connecting");try{const ticket=await api.realtimeTicket();if(disposed)return;const ws=new WebSocket(websocketUrl(ticket.ticket));socketRef.current=ws;ws.onopen=()=>{setSocketState("connected");if(selectedRef.current)ws.send(JSON.stringify({event:"support:subscribe",data:{conversation_id:selectedRef.current}}));};ws.onmessage=(ev)=>{try{const packet=JSON.parse(ev.data);const message=packet?.data?.message;if(message&&selectedRef.current===Number(message.conversation_id||packet.conversation_id)){setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,message)}:d);sequenceRef.current=Math.max(sequenceRef.current,Number(message.message_sequence||0));}if(["support:queue_updated","support:conversation_assigned","support:conversation_resolved"].includes(packet.event))void loadList();}catch{}};ws.onclose=()=>{setSocketState("offline");if(!disposed)reconnect=window.setTimeout(connect,2000);};ws.onerror=()=>ws.close();}catch{setSocketState("offline");if(!disposed)reconnect=window.setTimeout(connect,3000);}};void connect();return()=>{disposed=true;if(reconnect)clearTimeout(reconnect);socketRef.current?.close();};},[staff?.id,loadList]);
  useEffect(()=>{streamAbortRef.current?.abort();if(!staff||!selectedId)return;const controller=new AbortController();streamAbortRef.current=controller;let retry:number|undefined;const connect=async()=>{setStreamStatus("syncing");try{const response=await openStaffConversationStream(selectedId,sequenceRef.current,controller.signal);setStreamStatus("live");await consumeStaffEventStream(response,(packet)=>{const message=packet.data?.message;if(message){setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,message)}:d);sequenceRef.current=Math.max(sequenceRef.current,Number(message.message_sequence||0));requestAnimationFrame(()=>{const el=messagePaneRef.current;if(el&&el.scrollHeight-el.scrollTop-el.clientHeight<180)el.scrollTop=el.scrollHeight;});}if(packet.event==="conversation.resolved"||packet.event==="conversation.assigned")void loadConversation(selectedId);},controller.signal);}catch{if(!controller.signal.aborted){setStreamStatus("fallback");retry=window.setTimeout(connect,2500);}}};void connect();return()=>{controller.abort();if(retry)clearTimeout(retry);};},[staff?.id,selectedId,loadConversation]);

  async function changePresence(status:"active"|"invisible"){if(!staff)return;await api.presence(status);setStaff({...staff,availability_status:status});}
  async function accept(item:Conversation){try{await api.accept(item.id);setView("conversations");setTab("mine");await loadConversation(item.id);await loadList();}catch(c){setError(c instanceof Error?c.message:"Could not accept conversation");}}
  async function send(){if(!detail||!draft.trim()||!canReply)return;const text=draft;setDraft("");try{const result=await api.reply(detail.conversation.id,text);setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,result.message)}:d);}catch(c){setDraft(text);setError(c instanceof Error?c.message:"Message failed");}}
  async function addNote(){if(!detail)return;const note=prompt("Internal note (customer cannot see this):");if(!note)return;await api.note(detail.conversation.id,note);await loadConversation(detail.conversation.id);}
  async function transfer(){if(!detail)return;const active=onlineStaff.filter((x)=>x.id!==staff?.id&&x.availability_status==="active");if(!active.length){setError("No other Active staff member is available.");return;}const name=prompt(`Transfer to: ${active.map((x)=>`${x.id}=${x.display_name}`).join(", ")}`);const target=active.find((x)=>String(x.id)===String(name)||x.display_name.toLowerCase()===String(name||"").toLowerCase());if(!target)return;const reason=prompt("Transfer reason:")||"Customer needs another representative";await api.transfer(detail.conversation.id,target.id,reason);await loadConversation(detail.conversation.id);}
  async function transferDecision(id:number,action:"accept"|"reject"){try{await api.transferDecision(id,action);await refresh();if(action==="accept"){const request=transferRequests.find((x)=>Number(x.id)===id);if(request?.conversation_id){setView("conversations");setTab("mine");await loadConversation(Number(request.conversation_id));}}}catch(c){setError(c instanceof Error?c.message:"Transfer decision failed");}}
  async function resolve(){if(!detail)return;if(!confirm("Resolve and return the customer to platform support?"))return;await api.resolve(detail.conversation.id);await loadConversation(detail.conversation.id);await loadList();}
  async function upload(file:File){if(!detail||!canUpload)return;setUploading(true);try{const result=await api.uploadAttachment(detail.conversation.id,file);setDetail((d)=>d?{...d,messages:mergeMessage(d.messages,result.message)}:d);}catch(c){setError(c instanceof Error?c.message:"Upload failed");}finally{setUploading(false);if(fileRef.current)fileRef.current.value="";}}
  function insertQuickReply(reply:QuickReply){if(!canReply)return;setDraft((current)=>current?`${current}\n${reply.message_text}`:reply.message_text);}
  async function createPersonalReply(){const title=prompt("Quick reply title:");if(!title)return;const message=prompt("Quick reply message:");if(!message)return;await api.createQuickReply({title,message_text:message,category:"Personal"});setQuickReplies(await api.quickReplies());}
  async function logout(){try{await api.logout();}catch{}saveToken("");setStaff(null);}

  if(!staff)return <Login onLogin={(s,st)=>{setStaff(s);setSettings(st);}}/>;
  return <div className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><Headphones/><div><strong>Support Workspace</strong><small>{staff.display_name}</small></div></div><nav>
      <button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}><LayoutDashboard/>Dashboard</button>
      <button className={view==="conversations"?"active":""} onClick={()=>setView("conversations")}><MessageCircle/>Conversations</button>
      <button className={view==="archive"?"active":""} onClick={()=>{setView("archive");setTab("closed");}}><Archive/>Archive</button>
      <button className={view==="performance"?"active":""} onClick={()=>setView("performance")}><BarChart3/>Performance</button>
    </nav><div className="sidebar-footer"><div className={`connection ${socketState}`}><span/>{socketState==="connected"?"Realtime connected":socketState==="offline"?"Fallback syncing":"Reconnecting"}</div><button onClick={logout}><LogOut/>Logout</button></div></aside>
    <section className="workspace-shell"><header className="topbar"><div><h1>{view==="dashboard"?"Dashboard":view==="performance"?"Performance":"Customer Conversations"}</h1><p>{staff.email}</p></div><div className="top-actions"><div className="availability"><button className={staff.availability_status==="active"?"active":""} onClick={()=>changePresence("active")}>Active</button><button className={staff.availability_status==="invisible"?"active":""} onClick={()=>changePresence("invisible")}>Invisible</button></div><button className="icon-button" onClick={refresh}><RefreshCw/></button></div></header>{error&&<div className="global-error">{error}<button onClick={()=>setError("")}>×</button></div>}
      {view==="dashboard"&&<Dashboard conversations={conversations} performance={performance} transferRequests={transferRequests} onOpen={(id)=>{setView("conversations");void loadConversation(id);}} onAccept={accept} onTransferDecision={transferDecision} zone={zone}/>} 
      {(view==="conversations"||view==="archive")&&<div className="professional-workspace">
        <aside className="conversation-rail"><div className="queue-tabs">{queueTabs.filter((x)=>view!=="archive"||x.key==="closed").map((x)=><button className={tab===x.key?"active":""} key={x.key} onClick={()=>{setTab(x.key);setDetail(null);setSelectedId(null);}}>{x.label}</button>)}</div><div className="search-box"><Search/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search conversations"/></div><div className="conversation-list">{filtered.map((item)=><article key={item.id} className={selectedId===item.id?"selected":""} onClick={()=>loadConversation(item.id)}><div className="list-head"><span className="avatar"><UserRound/></span><div><strong>{item.customer_display_name||item.customer_identifier||`Customer ${item.id}`}</strong><small>#{item.id} · {formatDate(item.last_message_at||item.queue_entered_at,zone)}</small></div>{Number(item.unread_count||0)>0&&<b>{item.unread_count}</b>}</div><p>{item.last_message||statusLabel(item.handoff_reason||item.status)}</p><footer><span className={`status-dot ${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span>{tab==="waiting"&&<button onClick={(e)=>{e.stopPropagation();void accept(item);}}>Accept</button>}</footer></article>)}{!filtered.length&&<div className="empty-list">No conversations.</div>}</div></aside>
        <main className="conversation-main">{detail?<><header className="conversation-header"><div><h2>{detail.conversation.customer_display_name||detail.conversation.customer_identifier||`Customer ${detail.conversation.id}`}</h2><p><span className={`status-dot ${detail.conversation.status.toLowerCase()}`}>{statusLabel(detail.conversation.status)}</span> · {detail.conversation.assigned_staff_name||"Unassigned"} · {streamStatus==="live"?"Live":streamStatus==="fallback"?"Fallback sync":"Syncing"}</p></div><div className="conversation-actions"><button onClick={addNote}><StickyNote/>Note</button>{canReply&&<button onClick={transfer}><ArrowRightLeft/>Transfer</button>}{canReply&&<button className="resolve" onClick={resolve}><CheckCircle2/>Resolve</button>}<button><MoreHorizontal/></button></div></header><div className="message-pane" ref={messagePaneRef}>{detail.messages.filter((m)=>!m.is_internal).map((m)=><MessageBubble key={m.id} message={m} zone={zone}/>)}</div><footer className="composer"><div className="composer-toolbar"><button className="active">Reply</button><button onClick={addNote}>Internal Note</button><span/>{canUpload&&<><button title="Upload image or file" onClick={()=>fileRef.current?.click()}><Paperclip/></button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp,application/pdf,text/plain" onChange={(e)=>e.target.files?.[0]&&void upload(e.target.files[0])}/></>}<button onClick={()=>setRightTab("shortcuts")}><Zap/></button></div><div className="composer-input"><textarea disabled={!canReply||uploading} value={draft} onChange={(e)=>setDraft(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder={canReply?"Type a reply…":`Read-only — assigned to ${detail.conversation.assigned_staff_name||"another representative"}`}/><button disabled={!canReply||!draft.trim()||uploading} onClick={send}><Send/></button></div></footer></>:<div className="empty-conversation"><MessageCircle/><h2>Select a conversation</h2><p>Waiting conversations can be accepted directly by Active staff.</p></div>}</main>
        <aside className="context-panel"><div className="right-tabs"><button className={rightTab==="conversation"?"active":""} onClick={()=>setRightTab("conversation")}>Conversation</button><button className={rightTab==="shortcuts"?"active":""} onClick={()=>setRightTab("shortcuts")}>Shortcuts</button></div>{rightTab==="conversation"?<ConversationContext detail={detail} context={context} zone={zone}/>:<Shortcuts replies={shownQuickReplies} search={quickSearch} onSearch={setQuickSearch} onUse={insertQuickReply} onCreate={createPersonalReply}/>}</aside>
      </div>}
      {view==="performance"&&<Performance data={performance}/>} 
    </section>
  </div>;
}

function MessageBubble({message,zone}:{message:SupportMessage;zone:string}){
  if(message.sender_type==="SYSTEM")return <div className="system-message"><Activity/><span>{message.body_text}</span><time>{formatDate(message.created_at,zone)}</time></div>;
  const image=message.message_type==="image"&&message.attachment_url;
  const file=message.message_type==="attachment"&&message.attachment_url;
  return <div className={`message ${message.sender_type.toLowerCase()}`}><div className="message-author"><strong>{message.sender_name||message.sender_type}</strong><time>{formatDate(message.created_at,zone)}</time></div>{image&&<a href={message.attachment_url} target="_blank" rel="noreferrer"><img src={message.attachment_url} alt={message.attachment_name||"Shared image"}/></a>}{file&&<a className="file-card" href={message.attachment_url} target="_blank" rel="noreferrer"><FileText/><span><strong>{message.attachment_name||"Attachment"}</strong><small>{message.attachment_content_type||"File"}</small></span></a>}{message.body_text&&<p>{message.body_text}</p>}{message.sender_type==="STAFF"&&<small className="delivery">{message.read_at?"Read":message.delivered_at?"Delivered":"Sent"}</small>}</div>;
}
function ConversationContext({detail,context,zone}:{detail:ConversationDetail|null;context:Record<string,any>|null;zone:string}){if(!detail)return <div className="right-empty"><UserRound/><p>Select a conversation to view customer information.</p></div>;return <div className="context-sections"><section><h3>Visitor Information</h3><dl><dt>Customer</dt><dd>{detail.conversation.customer_display_name||detail.conversation.customer_identifier||"Not set"}</dd><dt>Language</dt><dd>{detail.conversation.customer_locale||"Not set"}</dd><dt>IP address</dt><dd>{context?.ip_address||"Not available"}</dd><dt>Region</dt><dd>{[context?.region_name,context?.country_code].filter(Boolean).join(", ")||"Not available"}</dd></dl></section><section><h3>Device Information</h3><dl><dt>Device</dt><dd>{context?.device_type||"Not available"}</dd><dt>Operating system</dt><dd>{context?.operating_system||"Not available"}</dd><dt>Browser</dt><dd>{[context?.browser_name,context?.browser_version].filter(Boolean).join(" ")||"Not available"}</dd><dt>Current page</dt><dd className="break">{context?.current_url||"Not available"}</dd></dl></section><section><h3>Conversation</h3><dl><dt>Started</dt><dd>{formatDate(detail.conversation.created_at||detail.conversation.queue_entered_at,zone)}</dd><dt>Handoff reason</dt><dd>{statusLabel(detail.conversation.handoff_reason||"Not specified")}</dd><dt>Assigned</dt><dd>{detail.conversation.assigned_staff_name||"Unassigned"}</dd><dt>Control</dt><dd>{detail.conversation.control_mode}</dd></dl></section><section><h3>Internal Notes</h3>{detail.notes.map((n)=><article className="note" key={n.id}><p>{n.note_text}</p><small>{n.author_name||"Staff"} · {formatDate(n.created_at,zone)}</small></article>)}{!detail.notes.length&&<p className="muted">No internal notes.</p>}</section></div>}
function Shortcuts({replies,search,onSearch,onUse,onCreate}:{replies:QuickReply[];search:string;onSearch:(v:string)=>void;onUse:(r:QuickReply)=>void;onCreate:()=>void}){return <div className="shortcuts"><div className="search-box"><Search/><input value={search} onChange={(e)=>onSearch(e.target.value)} placeholder="Search quick replies"/></div><button className="create-shortcut" onClick={onCreate}><Plus/>New personal reply</button>{replies.map((r)=><article key={r.id} onClick={()=>onUse(r)}><header><strong>{r.title}</strong><span>{r.scope_kind}</span></header><small>{r.category}{r.shortcut?` · ${r.shortcut}`:""}</small><p>{r.message_text}</p></article>)}{!replies.length&&<p className="muted">No quick replies available.</p>}</div>}
function Dashboard({conversations,performance,transferRequests,onOpen,onAccept,onTransferDecision,zone}:{conversations:Conversation[];performance:Record<string,any>;transferRequests:Array<Record<string,any>>;onOpen:(id:number)=>void;onAccept:(c:Conversation)=>void;onTransferDecision:(id:number,action:"accept"|"reject")=>void;zone:string}){const waiting=conversations.filter((x)=>x.status==="WAITING_FOR_AGENT");return <div className="dashboard"><div className="metric-grid"><Metric icon={Users} label="Waiting" value={waiting.length}/><Metric icon={MessageCircle} label="Served today" value={Number(performance.conversations_served||0)}/><Metric icon={CheckCircle2} label="Resolved" value={Number(performance.resolved_conversations||0)}/><Metric icon={Clock3} label="First response" value={formatDuration(performance.avg_first_response_seconds)}/></div>{transferRequests.length>0&&<section className="dashboard-table transfer-requests"><header><div><h2>Transfer Requests</h2><p>Ownership changes only after you accept.</p></div></header>{transferRequests.map((request)=><article key={request.id}><div><strong>{request.customer_display_name||request.customer_identifier||`Conversation ${request.conversation_id}`}</strong><p>{request.reason||"Transfer requested"}</p><small>From {request.from_staff_name||"another representative"}</small></div><div className="transfer-actions"><button onClick={()=>onTransferDecision(Number(request.id),"reject")}>Reject</button><button className="primary-button" onClick={()=>onTransferDecision(Number(request.id),"accept")}>Accept</button></div></article>)}</section>}<section className="dashboard-table"><header><div><h2>Waiting Queue</h2><p>Active staff can accept conversations directly.</p></div></header>{waiting.slice(0,8).map((c)=><article key={c.id}><div><strong>{c.customer_display_name||c.customer_identifier||`Customer ${c.id}`}</strong><p>{c.last_message||statusLabel(c.handoff_reason||"New request")}</p><small>{formatDate(c.queue_entered_at,zone)}</small></div><button onClick={()=>onAccept(c)}>Accept</button></article>)}{!waiting.length&&<div className="empty-list">No customers are waiting.</div>}</section></div>}
function Performance({data}:{data:Record<string,any>}){return <div className="performance"><div className="metric-grid"><Metric icon={Users} label="Conversations" value={Number(data.conversations_served||0)}/><Metric icon={CheckCircle2} label="Resolved" value={Number(data.resolved_conversations||0)}/><Metric icon={Send} label="Replies" value={Number(data.replies_sent||0)}/><Metric icon={Clock3} label="Handling" value={formatDuration(data.avg_conversation_seconds)}/></div><section><h2>Professional service metrics</h2><p>Replies and resolved conversations are primary metrics. Sentence count is informational only.</p></section></div>}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}){return <article className="metric"><Icon/><div><span>{label}</span><strong>{value}</strong></div></article>}
